import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { AppError } from '../../../errors/app-error.js';
import { requireAuthentication } from '../../../auth/auth-hook.js';
import type { AuthenticationProvider } from '../../../auth/authentication-provider.js';
import type { PlatformManagementService } from '../application/services/index.js';
import type { FeatureFlagUseCases, RuntimeConfigUseCases, AppVersionUseCases, AnnouncementUseCases, RegionUseCases } from '../application/use-cases/index.js';
import type { OperationsAuthorizer, OperationsAuditRecorder, OperatorPermissionKey, AuthorizedOperatorContext } from '../../operations/public/index.js';

const parse=<T>(s:z.ZodType<T>,v:unknown):T=>{const r=s.safeParse(v);if(!r.success)throw new AppError({code:'PLATFORM_INVALID_ARGUMENT',message:'Request validation failed',httpStatus:400,details:r.error.issues});return r.data;};
const ff=z.object({key:z.string().regex(/^[a-z][a-z0-9_]{0,99}$/)}).strict(); const region=z.object({code:z.string().regex(/^[A-Z][A-Z0-9_]{1,7}$/)}).strict(); const ann=z.object({announcement_id:z.string().uuid()}).strict(); const av=z.object({client_platform:z.enum(['android','ios']),build_number:z.coerce.number().int().positive()}).strict();
export type PlatformManagementRouteDeps={authentication:AuthenticationProvider;authorizer:OperationsAuthorizer;audit:OperationsAuditRecorder;management:PlatformManagementService;featureFlags:FeatureFlagUseCases;runtimeConfigs:RuntimeConfigUseCases;appVersions:AppVersionUseCases;announcements:AnnouncementUseCases;regions:RegionUseCases};
export async function registerPlatformManagementRoutes(app:FastifyInstance,d:PlatformManagementRouteDeps){const auth=requireAuthentication(d.authentication);const actor=(req:FastifyRequest,p:OperatorPermissionKey)=>d.authorizer.requirePermission(req.authContext!,p);const audit=async(req:FastifyRequest,o:AuthorizedOperatorContext,actionKey:string,target?:{domain:string;type:string;id?:string},details?:Record<string,unknown>)=>d.audit.recordSuccessfulAction({operator:o,actionKey,target,requestContext:{requestId:req.id,ipAddress:req.ip},details});
 app.get('/api/v1/admin/platform/feature-flags',{preHandler:auth},async req=>{await actor(req,'platform.feature_flags.read');return{items:await d.featureFlags.listFeatureFlagsForManagement((req.server as any).database??undefined)};});
 app.post('/api/v1/admin/platform/feature-flags',{preHandler:auth},async(req,reply)=>{const o=await actor(req,'platform.feature_flags.write');const b=parse(z.object({key:z.string(),name:z.string(),description:z.string().nullable().optional(),default_enabled:z.boolean().optional()}).strict(),req.body);const r=await d.management.createFeatureFlag({key:b.key,name:b.name,description:b.description,defaultEnabled:b.default_enabled});await audit(req,o,'platform.feature_flags.write',{domain:'platform',type:'feature_flag'}, {key:b.key});return reply.code(201).send(r);});
 app.patch('/api/v1/admin/platform/feature-flags/:key',{preHandler:auth},async req=>{const o=await actor(req,'platform.feature_flags.write');const p=parse(ff,req.params);const b=parse(z.object({name:z.string().optional(),description:z.string().nullable().optional(),default_enabled:z.boolean().optional(),status:z.enum(['active','inactive']).optional()}).strict(),req.body);const r=await d.management.updateFeatureFlag(p.key,{name:b.name,description:b.description,defaultEnabled:b.default_enabled,status:b.status});await audit(req,o,'platform.feature_flags.write',{domain:'platform',type:'feature_flag'},{key:p.key});return r;});
 app.post('/api/v1/admin/platform/feature-flags/:key/retire',{preHandler:auth},async req=>{const o=await actor(req,'platform.feature_flags.write');const p=parse(ff,req.params);const r=await d.management.retireFeatureFlag(p.key);await audit(req,o,'platform.feature_flags.write',{domain:'platform',type:'feature_flag'},{key:p.key,command:'retire'});return r;});
 app.get('/api/v1/admin/platform/runtime-configs',{preHandler:auth},async req=>{await actor(req,'platform.runtime_configs.read');return{items:await d.runtimeConfigs.listRuntimeConfigsForManagement()};});
 app.put('/api/v1/admin/platform/runtime-configs/:key',{preHandler:auth},async req=>{const o=await actor(req,'platform.runtime_configs.write');const p=parse(z.object({key:z.string()}).strict(),req.params);const b=parse(z.object({value_type:z.enum(['string','number','boolean','json']),value:z.unknown(),description:z.string().nullable().optional(),expected_updated_at:z.coerce.date().optional()}).strict(),req.body);const r=await d.management.setRuntimeConfig({key:p.key,valueType:b.value_type,value:b.value,description:b.description,expectedUpdatedAt:b.expected_updated_at});await audit(req,o,'platform.runtime_configs.write',{domain:'platform',type:'runtime_config'},{key:p.key});return r;});
 app.post('/api/v1/admin/platform/runtime-configs/:key/retire',{preHandler:auth},async req=>{const o=await actor(req,'platform.runtime_configs.write');const p=parse(z.object({key:z.string()}).strict(),req.params);const r=await d.management.retireRuntimeConfig(p.key);await audit(req,o,'platform.runtime_configs.write',{domain:'platform',type:'runtime_config'},{key:p.key,command:'retire'});return r;});
 app.post('/api/v1/admin/platform/app-versions',{preHandler:auth},async(req,reply)=>{const o=await actor(req,'platform.app_versions.write');const b=parse(z.object({client_platform:z.enum(['android','ios']),version:z.string(),build_number:z.number().int().positive(),release_notes:z.string().nullable().optional()}).strict(),req.body);const r=await d.management.createAppVersionDraft({clientPlatform:b.client_platform,version:b.version,buildNumber:b.build_number,releaseNotes:b.release_notes});await audit(req,o,'platform.app_versions.write',{domain:'platform',type:'app_version'},{client_platform:b.client_platform,build_number:b.build_number});return reply.code(201).send(r);});
 app.post('/api/v1/admin/platform/app-versions/:client_platform/:build_number/publish',{preHandler:auth},async req=>{const o=await actor(req,'platform.app_versions.write');const p=parse(av,req.params);const r=await d.management.publishAppVersion(p.client_platform,p.build_number);await audit(req,o,'platform.app_versions.write',{domain:'platform',type:'app_version'},{client_platform:p.client_platform,build_number:p.build_number,command:'publish'});return r;});
 app.post('/api/v1/admin/platform/announcements',{preHandler:auth},async(req,reply)=>{const o=await actor(req,'platform.announcements.write');const b=parse(z.object({title:z.string(),content:z.string(),region_code:z.string().nullable().optional(),client_platform:z.enum(['android','ios']).nullable().optional(),starts_at:z.coerce.date().nullable().optional(),ends_at:z.coerce.date().nullable().optional()}).strict(),req.body);const r=await d.management.createAnnouncementDraft({title:b.title,content:b.content,regionCode:b.region_code,clientPlatform:b.client_platform,startsAt:b.starts_at,endsAt:b.ends_at});await audit(req,o,'platform.announcements.write',{domain:'platform',type:'announcement',id:(r as any).publicId});return reply.code(201).send(r);});
 app.post('/api/v1/admin/platform/announcements/:announcement_id/publish',{preHandler:auth},async req=>{const o=await actor(req,'platform.announcements.write');const p=parse(ann,req.params);const r=await d.management.publishAnnouncement(p.announcement_id);await audit(req,o,'platform.announcements.write',{domain:'platform',type:'announcement',id:p.announcement_id},{command:'publish'});return r;});
 app.post('/api/v1/admin/platform/regions',{preHandler:auth},async(req,reply)=>{const o=await actor(req,'platform.regions.write');const b=parse(z.object({code:z.string(),name:z.string(),default_locale:z.string(),timezone:z.string()}).strict(),req.body);const r=await d.management.createRegion({code:b.code,name:b.name,defaultLocale:b.default_locale,timezone:b.timezone});await audit(req,o,'platform.regions.write',{domain:'platform',type:'region'},{code:b.code});return reply.code(201).send(r);});
 app.post('/api/v1/admin/platform/regions/:code/retire',{preHandler:auth},async req=>{const o=await actor(req,'platform.regions.write');const p=parse(region,req.params);const r=await d.management.retireRegion(p.code);await audit(req,o,'platform.regions.write',{domain:'platform',type:'region'},{code:p.code,command:'retire'});return r;});
}
