import type { FastifyInstance,FastifyRequest } from 'fastify';
import { z } from 'zod';
import { AppError } from '../../../errors/app-error.js';
import { requireAuthentication } from '../../../auth/auth-hook.js';
import type { AuthenticationProvider } from '../../../auth/authentication-provider.js';
import type { DatabaseExecutor } from '../../../database/executor.js';
import type { PlatformManagementService } from '../application/services/index.js';
import type { FeatureFlagUseCases,RuntimeConfigUseCases,AppVersionUseCases,AnnouncementUseCases,RegionUseCases,MenuUseCases } from '../application/use-cases/index.js';
import type { FeatureFlag,RuntimeConfigRecord,AppVersionRecord,AnnouncementRecord,Region,MenuItem,MenuTreeNode } from '../domain/index.js';
import { MENU_ROUTE_TARGET_KEYS,parseMenuInternalId } from '../domain/index.js';
import type { OperationsAuthorizer,OperationsAuditRecorder,OperatorPermissionKey,AuthorizedOperatorContext } from '../../operations/public/index.js';

const parse=<T>(s:z.ZodType<T>,v:unknown):T=>{const r=s.safeParse(v);if(!r.success)throw new AppError({code:'PLATFORM_INVALID_ARGUMENT',message:'Request validation failed',httpStatus:400,details:r.error.issues});return r.data;};
const notFound=(message:string)=>new AppError({code:'PLATFORM_NOT_FOUND',message,httpStatus:404});
const ff=z.object({key:z.string().regex(/^[a-z][a-z0-9_]{0,99}$/)}).strict();
const region=z.object({code:z.string().regex(/^[A-Z][A-Z0-9_]{1,7}$/)}).strict();
const ann=z.object({announcement_id:z.string().uuid()}).strict();
const av=z.object({client_platform:z.enum(['android','ios']),build_number:z.coerce.number().int().positive()}).strict();
const runtimeKey=z.object({key:z.string().regex(/^[a-z][a-z0-9_]{0,99}$/)}).strict();
const overrideBody=z.object({region_code:z.string().regex(/^[A-Z][A-Z0-9_]{1,7}$/).nullable().optional(),client_platform:z.enum(['android','ios']).nullable().optional(),enabled:z.boolean()}).strict();
const overrideDelete=z.object({region_code:z.string().regex(/^[A-Z][A-Z0-9_]{1,7}$/).nullable().optional(),client_platform:z.enum(['android','ios']).nullable().optional()}).strict();
const flagDto=(r:FeatureFlag)=>({key:r.key,name:r.name,description:r.description,default_enabled:r.defaultEnabled,status:r.status,created_at:r.createdAt.toISOString(),updated_at:r.updatedAt.toISOString()});
const configDto=(r:RuntimeConfigRecord)=>({key:r.key,value_type:r.valueType,value:r.value,description:r.description,status:r.status,created_at:r.createdAt.toISOString(),updated_at:r.updatedAt.toISOString()});
const versionDto=(r:AppVersionRecord)=>({client_platform:r.clientPlatform,version:r.version,build_number:r.buildNumber,status:r.status,update_policy:r.updatePolicy,release_notes:r.releaseNotes,released_at:r.releasedAt?.toISOString()??null,created_at:r.createdAt.toISOString(),updated_at:r.updatedAt.toISOString()});
const regionDto=(r:Region)=>({code:r.code,name:r.name,default_locale:r.defaultLocale,timezone:r.timezone,status:r.status,created_at:r.createdAt.toISOString(),updated_at:r.updatedAt.toISOString()});
const menuItemDto=(r:MenuItem)=>({id:Number(r.id),label:r.label,route_key:r.routeKey,icon:r.icon,sort_order:r.sortOrder,status:r.status,created_at:r.createdAt.toISOString(),updated_at:r.updatedAt.toISOString()});
const menuTreeDto=(n:MenuTreeNode):Record<string,unknown>=>({id:Number(n.id),label:n.label,route_key:n.routeKey,icon:n.icon,sort_order:n.sortOrder,status:n.status,updated_at:n.updatedAt.toISOString(),permissions:n.permissions,children:n.children.map(menuTreeDto)});
const menuId=z.object({id:z.coerce.number().int().positive()}).strict();
const menuParentId=z.object({parent_id:z.coerce.number().int().positive()}).strict();
const announcementDto=(r:AnnouncementRecord,regionCode:string|null)=>({announcement_id:r.publicId,title:r.title,content:r.content,region_code:regionCode,client_platform:r.clientPlatform,status:r.status,starts_at:r.startsAt?.toISOString()??null,ends_at:r.endsAt?.toISOString()??null,created_at:r.createdAt.toISOString(),updated_at:r.updatedAt.toISOString()});
export type PlatformManagementRouteDeps={executor:DatabaseExecutor;authentication:AuthenticationProvider;authorizer:OperationsAuthorizer;audit:OperationsAuditRecorder;management:PlatformManagementService;featureFlags:FeatureFlagUseCases;runtimeConfigs:RuntimeConfigUseCases;appVersions:AppVersionUseCases;announcements:AnnouncementUseCases;regions:RegionUseCases;menuUseCases?:MenuUseCases|undefined};

export async function registerPlatformManagementRoutes(app:FastifyInstance,d:PlatformManagementRouteDeps){
 const auth=requireAuthentication(d.authentication);
 const actor=(req:FastifyRequest,p:OperatorPermissionKey)=>d.authorizer.requirePermission(req.authContext!,p);
 const audit=async(req:FastifyRequest,o:AuthorizedOperatorContext,actionKey:string,target?:{domain:string;type:string;id?:string},details?:Record<string,unknown>)=>d.audit.recordSuccessfulAction({operator:o,actionKey,requestContext:{requestId:req.id,ipAddress:req.ip},...(target?{target}:{}),...(details?{details}:{})});
 const regionCodeMap=async()=>new Map((await d.regions.listRegionsForManagement(d.executor)).map(r=>[String(r.id),r.code]));

 app.get('/api/v1/admin/platform/feature-flags',{preHandler:auth},async req=>{await actor(req,'platform.feature_flags.read');return{items:(await d.featureFlags.listFeatureFlagsForManagement(d.executor)).map(flagDto)};});
 app.get('/api/v1/admin/platform/feature-flags/:key',{preHandler:auth},async req=>{await actor(req,'platform.feature_flags.read');const p=parse(ff,req.params);const r=(await d.featureFlags.listFeatureFlagsForManagement(d.executor)).find(x=>x.key===p.key);if(!r)throw notFound(`Feature flag '${p.key}' not found`);return{feature_flag:flagDto(r)};});
 app.post('/api/v1/admin/platform/feature-flags',{preHandler:auth},async(req,reply)=>{const o=await actor(req,'platform.feature_flags.write');const b=parse(z.object({key:z.string(),name:z.string(),description:z.string().nullable().optional(),default_enabled:z.boolean().optional()}).strict(),req.body);const r=await d.management.createFeatureFlag({key:b.key,name:b.name,...(b.description!==undefined?{description:b.description}:{}),...(b.default_enabled!==undefined?{defaultEnabled:b.default_enabled}:{})});await audit(req,o,'platform.feature_flags.write',{domain:'platform',type:'feature_flag'},{key:b.key,command:'create'});return reply.code(201).send({feature_flag:flagDto(r)});});
 app.patch('/api/v1/admin/platform/feature-flags/:key',{preHandler:auth},async req=>{const o=await actor(req,'platform.feature_flags.write');const p=parse(ff,req.params);const b=parse(z.object({name:z.string().optional(),description:z.string().nullable().optional(),default_enabled:z.boolean().optional(),status:z.enum(['active','inactive']).optional()}).strict(),req.body);const r=await d.management.updateFeatureFlag(p.key,{...(b.name!==undefined?{name:b.name}:{}),...(b.description!==undefined?{description:b.description}:{}),...(b.default_enabled!==undefined?{defaultEnabled:b.default_enabled}:{}),...(b.status!==undefined?{status:b.status}:{})});await audit(req,o,'platform.feature_flags.write',{domain:'platform',type:'feature_flag'},{key:p.key,command:'update'});return{feature_flag:flagDto(r)};});
 app.post('/api/v1/admin/platform/feature-flags/:key/retire',{preHandler:auth},async req=>{const o=await actor(req,'platform.feature_flags.write');const p=parse(ff,req.params);const r=await d.management.retireFeatureFlag(p.key);await audit(req,o,'platform.feature_flags.write',{domain:'platform',type:'feature_flag'},{key:p.key,command:'retire'});return{feature_flag:flagDto(r)};});
 app.put('/api/v1/admin/platform/feature-flags/:key/override',{preHandler:auth},async req=>{const o=await actor(req,'platform.feature_flags.write');const p=parse(ff,req.params);const b=parse(overrideBody,req.body);await d.management.setFeatureFlagOverride({key:p.key,...(b.region_code!==undefined?{regionCode:b.region_code}:{}),...(b.client_platform!==undefined?{clientPlatform:b.client_platform}:{}),enabled:b.enabled});await audit(req,o,'platform.feature_flags.write',{domain:'platform',type:'feature_flag'},{key:p.key,command:'set_override',region_code:b.region_code??null,client_platform:b.client_platform??null,enabled:b.enabled});return{key:p.key,region_code:b.region_code??null,client_platform:b.client_platform??null,enabled:b.enabled};});
 app.delete('/api/v1/admin/platform/feature-flags/:key/override',{preHandler:auth},async(req,reply)=>{const o=await actor(req,'platform.feature_flags.write');const p=parse(ff,req.params);const b=parse(overrideDelete,req.body??{});const changed=await d.management.removeFeatureFlagOverride({key:p.key,...(b.region_code!==undefined?{regionCode:b.region_code}:{}),...(b.client_platform!==undefined?{clientPlatform:b.client_platform}:{})});if(changed)await audit(req,o,'platform.feature_flags.write',{domain:'platform',type:'feature_flag'},{key:p.key,command:'remove_override',region_code:b.region_code??null,client_platform:b.client_platform??null});return reply.code(204).send();});

 app.get('/api/v1/admin/platform/runtime-configs',{preHandler:auth},async req=>{await actor(req,'platform.runtime_configs.read');return{items:(await d.runtimeConfigs.listRuntimeConfigsForManagement(d.executor)).map(configDto)};});
 app.get('/api/v1/admin/platform/runtime-configs/:key',{preHandler:auth},async req=>{await actor(req,'platform.runtime_configs.read');const p=parse(runtimeKey,req.params);const r=(await d.runtimeConfigs.listRuntimeConfigsForManagement(d.executor)).find(x=>x.key===p.key);if(!r)throw notFound(`Runtime config '${p.key}' not found`);return{runtime_config:configDto(r)};});
 app.put('/api/v1/admin/platform/runtime-configs/:key',{preHandler:auth},async req=>{const o=await actor(req,'platform.runtime_configs.write');const p=parse(runtimeKey,req.params);const b=parse(z.object({value_type:z.enum(['string','integer','number','boolean','json']),value:z.unknown(),description:z.string().nullable().optional(),expected_updated_at:z.coerce.date().optional()}).strict(),req.body);const r=await d.management.setRuntimeConfig({key:p.key,valueType:b.value_type,value:b.value,...(b.description!==undefined?{description:b.description}:{}),...(b.expected_updated_at!==undefined?{expectedUpdatedAt:b.expected_updated_at}:{})});await audit(req,o,'platform.runtime_configs.write',{domain:'platform',type:'runtime_config'},{key:p.key,command:'set'});return{runtime_config:configDto(r)};});
 app.post('/api/v1/admin/platform/runtime-configs/:key/retire',{preHandler:auth},async req=>{const o=await actor(req,'platform.runtime_configs.write');const p=parse(runtimeKey,req.params);const r=await d.management.retireRuntimeConfig(p.key);await audit(req,o,'platform.runtime_configs.write',{domain:'platform',type:'runtime_config'},{key:p.key,command:'retire'});return{runtime_config:configDto(r)};});

 app.get('/api/v1/admin/platform/app-versions',{preHandler:auth},async req=>{await actor(req,'platform.app_versions.read');const q=parse(z.object({client_platform:z.enum(['android','ios']).optional()}).strict(),req.query);return{items:(await d.appVersions.listAppVersionsForManagement(d.executor,q.client_platform)).map(versionDto)};});
 app.post('/api/v1/admin/platform/app-versions',{preHandler:auth},async(req,reply)=>{const o=await actor(req,'platform.app_versions.write');const b=parse(z.object({client_platform:z.enum(['android','ios']),version:z.string(),build_number:z.number().int().positive(),release_notes:z.string().nullable().optional()}).strict(),req.body);const r=await d.management.createAppVersionDraft({clientPlatform:b.client_platform,version:b.version,buildNumber:b.build_number,...(b.release_notes!==undefined?{releaseNotes:b.release_notes}:{})});await audit(req,o,'platform.app_versions.write',{domain:'platform',type:'app_version'},{client_platform:b.client_platform,build_number:b.build_number,command:'create'});return reply.code(201).send({app_version:versionDto(r)});});
 app.patch('/api/v1/admin/platform/app-versions/:client_platform/:build_number',{preHandler:auth},async req=>{const o=await actor(req,'platform.app_versions.write');const p=parse(av,req.params);const b=parse(z.object({version:z.string().optional(),release_notes:z.string().nullable().optional()}).strict(),req.body);const r=await d.management.updateAppVersionDraft(p.client_platform,p.build_number,{...(b.version!==undefined?{version:b.version}:{}),...(b.release_notes!==undefined?{releaseNotes:b.release_notes}:{})});await audit(req,o,'platform.app_versions.write',{domain:'platform',type:'app_version'},{client_platform:p.client_platform,build_number:p.build_number,command:'update_draft'});return{app_version:versionDto(r)};});
 app.post('/api/v1/admin/platform/app-versions/:client_platform/:build_number/publish',{preHandler:auth},async req=>{const o=await actor(req,'platform.app_versions.write');const p=parse(av,req.params);const r=await d.management.publishAppVersion(p.client_platform,p.build_number);await audit(req,o,'platform.app_versions.write',{domain:'platform',type:'app_version'},{client_platform:p.client_platform,build_number:p.build_number,command:'publish'});return{app_version:versionDto(r)};});
 app.post('/api/v1/admin/platform/app-versions/:client_platform/:build_number/policy',{preHandler:auth},async req=>{const o=await actor(req,'platform.app_versions.write');const p=parse(av,req.params);const b=parse(z.object({status:z.enum(['active','deprecated','blocked']),update_policy:z.enum(['none','optional','required']),expected_updated_at:z.coerce.date().optional()}).strict(),req.body);const r=await d.management.setAppVersionPolicy(p.client_platform,p.build_number,{status:b.status,updatePolicy:b.update_policy,...(b.expected_updated_at!==undefined?{expectedUpdatedAt:b.expected_updated_at}:{})});await audit(req,o,'platform.app_versions.write',{domain:'platform',type:'app_version'},{client_platform:p.client_platform,build_number:p.build_number,command:'policy'});return{app_version:versionDto(r)};});
 app.delete('/api/v1/admin/platform/app-versions/:client_platform/:build_number',{preHandler:auth},async(req,reply)=>{const o=await actor(req,'platform.app_versions.write');const p=parse(av,req.params);const changed=await d.management.deleteAppVersionDraft(p.client_platform,p.build_number);if(changed)await audit(req,o,'platform.app_versions.write',{domain:'platform',type:'app_version'},{client_platform:p.client_platform,build_number:p.build_number,command:'delete_draft'});return reply.code(204).send();});

 app.get('/api/v1/admin/platform/announcements',{preHandler:auth},async req=>{await actor(req,'platform.announcements.read');const codes=await regionCodeMap();return{items:(await d.announcements.listAnnouncementsForManagement(d.executor)).map(a=>announcementDto(a,a.regionId===null?null:codes.get(String(a.regionId))??null))};});
 app.get('/api/v1/admin/platform/announcements/:announcement_id',{preHandler:auth},async req=>{await actor(req,'platform.announcements.read');const p=parse(ann,req.params);const a=(await d.announcements.listAnnouncementsForManagement(d.executor)).find(x=>x.publicId===p.announcement_id);if(!a)throw notFound(`Announcement '${p.announcement_id}' not found`);const codes=await regionCodeMap();return{announcement:announcementDto(a,a.regionId===null?null:codes.get(String(a.regionId))??null)};});
 app.post('/api/v1/admin/platform/announcements',{preHandler:auth},async(req,reply)=>{const o=await actor(req,'platform.announcements.write');const b=parse(z.object({title:z.string(),content:z.string(),region_code:z.string().nullable().optional(),client_platform:z.enum(['android','ios']).nullable().optional(),starts_at:z.coerce.date().nullable().optional(),ends_at:z.coerce.date().nullable().optional()}).strict(),req.body);const r=await d.management.createAnnouncementDraft({title:b.title,content:b.content,...(b.region_code!==undefined?{regionCode:b.region_code}:{}),...(b.client_platform!==undefined?{clientPlatform:b.client_platform}:{}),...(b.starts_at!==undefined?{startsAt:b.starts_at}:{}),...(b.ends_at!==undefined?{endsAt:b.ends_at}:{})});await audit(req,o,'platform.announcements.write',{domain:'platform',type:'announcement',id:r.publicId},{command:'create'});return reply.code(201).send({announcement:announcementDto(r,b.region_code??null)});});
 app.patch('/api/v1/admin/platform/announcements/:announcement_id',{preHandler:auth},async req=>{const o=await actor(req,'platform.announcements.write');const p=parse(ann,req.params);const b=parse(z.object({title:z.string().optional(),content:z.string().optional(),region_code:z.string().nullable().optional(),client_platform:z.enum(['android','ios']).nullable().optional(),starts_at:z.coerce.date().nullable().optional(),ends_at:z.coerce.date().nullable().optional()}).strict(),req.body);const r=await d.management.updateAnnouncement(p.announcement_id,{...(b.title!==undefined?{title:b.title}:{}),...(b.content!==undefined?{content:b.content}:{}),...(b.region_code!==undefined?{regionCode:b.region_code}:{}),...(b.client_platform!==undefined?{clientPlatform:b.client_platform}:{}),...(b.starts_at!==undefined?{startsAt:b.starts_at}:{}),...(b.ends_at!==undefined?{endsAt:b.ends_at}:{})});await audit(req,o,'platform.announcements.write',{domain:'platform',type:'announcement',id:p.announcement_id},{command:'update'});const codes=await regionCodeMap();return{announcement:announcementDto(r,r.regionId===null?null:codes.get(String(r.regionId))??null)};});
 app.post('/api/v1/admin/platform/announcements/:announcement_id/publish',{preHandler:auth},async req=>{const o=await actor(req,'platform.announcements.write');const p=parse(ann,req.params);const r=await d.management.publishAnnouncement(p.announcement_id);await audit(req,o,'platform.announcements.write',{domain:'platform',type:'announcement',id:p.announcement_id},{command:'publish'});const codes=await regionCodeMap();return{announcement:announcementDto(r,r.regionId===null?null:codes.get(String(r.regionId))??null)};});
 app.post('/api/v1/admin/platform/announcements/:announcement_id/retire',{preHandler:auth},async req=>{const o=await actor(req,'platform.announcements.write');const p=parse(ann,req.params);const r=await d.management.retireAnnouncement(p.announcement_id);await audit(req,o,'platform.announcements.write',{domain:'platform',type:'announcement',id:p.announcement_id},{command:'retire'});const codes=await regionCodeMap();return{announcement:announcementDto(r,r.regionId===null?null:codes.get(String(r.regionId))??null)};});
 app.delete('/api/v1/admin/platform/announcements/:announcement_id',{preHandler:auth},async(req,reply)=>{const o=await actor(req,'platform.announcements.write');const p=parse(ann,req.params);const changed=await d.management.deleteAnnouncementDraft(p.announcement_id);if(changed)await audit(req,o,'platform.announcements.write',{domain:'platform',type:'announcement',id:p.announcement_id},{command:'delete_draft'});return reply.code(204).send();});

 app.get('/api/v1/admin/platform/regions',{preHandler:auth},async req=>{await actor(req,'platform.regions.read');return{items:(await d.regions.listRegionsForManagement(d.executor)).map(regionDto)};});
 app.get('/api/v1/admin/platform/regions/:code',{preHandler:auth},async req=>{await actor(req,'platform.regions.read');const p=parse(region,req.params);const r=await d.regions.getRegion(d.executor,p.code);if(!r)throw notFound(`Region '${p.code}' not found`);return{region:regionDto(r)};});
 app.post('/api/v1/admin/platform/regions',{preHandler:auth},async(req,reply)=>{const o=await actor(req,'platform.regions.write');const b=parse(z.object({code:z.string(),name:z.string(),default_locale:z.string(),timezone:z.string()}).strict(),req.body);const r=await d.management.createRegion({code:b.code,name:b.name,defaultLocale:b.default_locale,timezone:b.timezone});await audit(req,o,'platform.regions.write',{domain:'platform',type:'region'},{code:b.code,command:'create'});return reply.code(201).send({region:regionDto(r)});});
 app.patch('/api/v1/admin/platform/regions/:code',{preHandler:auth},async req=>{const o=await actor(req,'platform.regions.write');const p=parse(region,req.params);const b=parse(z.object({name:z.string().optional(),default_locale:z.string().optional(),timezone:z.string().optional(),status:z.enum(['active','inactive']).optional()}).strict(),req.body);const r=await d.management.updateRegion(p.code,{...(b.name!==undefined?{name:b.name}:{}),...(b.default_locale!==undefined?{defaultLocale:b.default_locale}:{}),...(b.timezone!==undefined?{timezone:b.timezone}:{}),...(b.status!==undefined?{status:b.status}:{})});await audit(req,o,'platform.regions.write',{domain:'platform',type:'region'},{code:p.code,command:'update'});return{region:regionDto(r)};});
 app.post('/api/v1/admin/platform/regions/:code/retire',{preHandler:auth},async req=>{const o=await actor(req,'platform.regions.write');const p=parse(region,req.params);const r=await d.management.retireRegion(p.code);await audit(req,o,'platform.regions.write',{domain:'platform',type:'region'},{code:p.code,command:'retire'});return{region:regionDto(r)};});

 // ---- Menu (ADR-022) ----
 const menuPermissionKeys=z.array(z.string().min(1)).max(100).optional();
 app.get('/api/v1/admin/platform/menus',{preHandler:auth},async req=>{await actor(req,'platform.menus.read');const tree=await d.management.listMenus();return{groups:tree.map(menuTreeDto)};});
 app.post('/api/v1/admin/platform/menus',{preHandler:auth},async(req,reply)=>{const o=await actor(req,'platform.menus.write');const b=parse(z.object({parent_id:z.coerce.number().int().positive().nullable().optional(),label:z.string(),route_key:z.string().nullable().optional(),icon:z.string().nullable().optional(),sort_order:z.number().int().min(0).optional(),permissions:menuPermissionKeys}).strict(),req.body);const r=await d.management.createMenu({...(b.parent_id!==undefined?{parentId:parseMenuInternalId(BigInt(b.parent_id!))}:{}),label:b.label,...(b.route_key!==undefined?{routeKey:b.route_key}:{}),...(b.icon!==undefined?{icon:b.icon}:{}),...(b.sort_order!==undefined?{sortOrder:b.sort_order}:{}),...(b.permissions!==undefined?{permissions:b.permissions}:{})});await audit(req,o,'platform.menus.write',{domain:'platform',type:'menu'},{command:'create',label:r.label});return reply.code(201).send({menu:menuItemDto(r)});});
 app.patch('/api/v1/admin/platform/menus/:id',{preHandler:auth},async req=>{const o=await actor(req,'platform.menus.write');const p=parse(menuId,req.params);const b=parse(z.object({label:z.string().optional(),route_key:z.string().nullable().optional(),icon:z.string().nullable().optional(),sort_order:z.number().int().min(0).optional(),status:z.enum(['active','disabled']).optional(),permissions:menuPermissionKeys,expected_updated_at:z.coerce.date().optional()}).strict(),req.body);const r=await d.management.updateMenu(parseMenuInternalId(BigInt(p.id)),{...(b.label!==undefined?{label:b.label}:{}),...(b.route_key!==undefined?{routeKey:b.route_key}:{}),...(b.icon!==undefined?{icon:b.icon}:{}),...(b.sort_order!==undefined?{sortOrder:b.sort_order}:{}),...(b.status!==undefined?{status:b.status}:{}),...(b.permissions!==undefined?{permissions:b.permissions}:{}),...(b.expected_updated_at!==undefined?{expectedUpdatedAt:b.expected_updated_at}:{})});await audit(req,o,'platform.menus.write',{domain:'platform',type:'menu'},{command:'update',label:r.label,status:r.status});return{menu:menuItemDto(r)};});
 app.post('/api/v1/admin/platform/menus/:id/remove',{preHandler:auth},async req=>{const o=await actor(req,'platform.menus.write');const p=parse(menuId,req.params);const b=parse(z.object({expected_updated_at:z.coerce.date().optional()}).strict(),req.body??{});const r=await d.management.removeMenu(parseMenuInternalId(BigInt(p.id)),b.expected_updated_at);await audit(req,o,'platform.menus.write',{domain:'platform',type:'menu'},{command:'remove'});return{menu:menuItemDto({...r,status:'removed'})};});
 app.put('/api/v1/admin/platform/menus/:parent_id/order',{preHandler:auth},async req=>{const o=await actor(req,'platform.menus.write');const p=parse(menuParentId,req.params);const b=parse(z.object({order:z.array(z.coerce.number().int().positive()).min(1),expected_updated_at:z.coerce.date().optional()}).strict(),req.body);const parentId=p.parent_id===0?null:parseMenuInternalId(BigInt(p.parent_id));const ids=await d.management.reorderMenus(parentId,{order:b.order.map((x:number)=>parseMenuInternalId(BigInt(x))),...(b.expected_updated_at!==undefined?{expectedUpdatedAt:b.expected_updated_at}:{})});await audit(req,o,'platform.menus.write',{domain:'platform',type:'menu'},{command:'reorder',parent_id:p.parent_id,order:ids.map((x:unknown)=>String(x))});return{reordered:ids.map((x:unknown)=>Number(x))};});
 app.post('/api/v1/admin/platform/menus/:id/move',{preHandler:auth},async req=>{const o=await actor(req,'platform.menus.write');const p=parse(menuId,req.params);const b=parse(z.object({parent_id:z.coerce.number().int().positive().nullable(),position:z.number().int().min(0),expected_updated_at:z.coerce.date(),source_layer_updated_at:z.coerce.date(),target_layer_updated_at:z.coerce.date()}).strict(),req.body);const r=await d.management.moveMenu(parseMenuInternalId(BigInt(p.id)),{parentId:b.parent_id===null?null:parseMenuInternalId(BigInt(b.parent_id)),position:b.position,expectedUpdatedAt:b.expected_updated_at,sourceLayerUpdatedAt:b.source_layer_updated_at,targetLayerUpdatedAt:b.target_layer_updated_at});await audit(req,o,'platform.menus.write',{domain:'platform',type:'menu',id:String(p.id)},{command:'move',to_parent_id:b.parent_id,position:b.position});return{menu:menuItemDto(r)};});
 app.get('/api/v1/admin/platform/route-targets',{preHandler:auth},async req=>{await actor(req,'platform.menus.read');return{route_targets:MENU_ROUTE_TARGET_KEYS};});
}
