import type { DatabaseExecutor } from '../../../database/executor.js';
import type { AuditPage,AuditRecord,AssignedRoleRecord,OperationsRepository,OperatorRecord,Page,RoleRecord } from '../application/ports/index.js';

type RowBase=Record<string,unknown>;
type OperatorRow=RowBase&{id:string;auth_subject_id:string;display_name:string;status:'active'|'disabled';created_at:Date;updated_at:Date;total?:number};
type RoleRow=RowBase&{id:string;code:string;name:string;description:string|null;status:'active'|'disabled';created_at:Date;updated_at:Date;assigned_at?:Date;total?:number};
type AuditRow=RowBase&{id:string;operator_id:string;action_key:string;target_domain:string|null;target_type:string|null;target_id:string|null;request_id:string|null;ip_address:string|null;details:Readonly<Record<string,unknown>>;created_at:Date};
type CountRow=RowBase&{count:string};type PermissionRow=RowBase&{permission_key:string};
const op=(r:OperatorRow):OperatorRecord=>({id:r.id,authSubjectId:r.auth_subject_id,displayName:r.display_name,status:r.status,createdAt:r.created_at,updatedAt:r.updated_at});
const role=(r:RoleRow):RoleRecord=>({id:r.id,code:r.code,name:r.name,description:r.description,status:r.status,createdAt:r.created_at,updatedAt:r.updated_at});
const audit=(r:AuditRow):AuditRecord=>({id:r.id,operatorId:r.operator_id,actionKey:r.action_key,targetDomain:r.target_domain,targetType:r.target_type,targetId:r.target_id,requestId:r.request_id,ipAddress:r.ip_address,details:r.details,createdAt:r.created_at});
export class PostgresOperationsRepository implements OperationsRepository{
 async lockBootstrap(db:DatabaseExecutor){await db.query('SELECT pg_advisory_xact_lock(904202608311::bigint)');}
 async findOperatorById(db:DatabaseExecutor,id:string,lock=false){const q=await db.query<OperatorRow>(`SELECT * FROM operations.operators WHERE id=$1${lock?' FOR UPDATE':''}`,[id]);return q.rows[0]?op(q.rows[0]):null;}
 async findOperatorByAuthSubjectId(db:DatabaseExecutor,id:string,lock=false){const q=await db.query<OperatorRow>(`SELECT * FROM operations.operators WHERE auth_subject_id=$1${lock?' FOR UPDATE':''}`,[id]);return q.rows[0]?op(q.rows[0]):null;}
 async listOperators(db:DatabaseExecutor,i:{page:number;pageSize:number;status?:'active'|'disabled'|undefined}):Promise<Page<OperatorRecord>>{const v:unknown[]=[];const where=i.status?(v.push(i.status),`WHERE status=$${v.length}`):'';v.push(i.pageSize,(i.page-1)*i.pageSize);const q=await db.query<OperatorRow>(`SELECT *, count(*) OVER()::int AS total FROM operations.operators ${where} ORDER BY created_at DESC,id ASC LIMIT $${v.length-1} OFFSET $${v.length}`,v);return{items:q.rows.map(op),total:Number(q.rows[0]?.total??0)};}
 async createOperator(db:DatabaseExecutor,i:{id:string;authSubjectId:string;displayName:string}){const q=await db.query<OperatorRow>('INSERT INTO operations.operators(id,auth_subject_id,display_name) VALUES($1,$2,$3) RETURNING *',[i.id,i.authSubjectId,i.displayName]);return op(q.rows[0]!);}
 async updateOperatorDisplayName(db:DatabaseExecutor,id:string,displayName:string){const q=await db.query<OperatorRow>('UPDATE operations.operators SET display_name=$2,updated_at=now() WHERE id=$1 RETURNING *',[id,displayName]);return q.rows[0]?op(q.rows[0]):null;}
 async updateOperatorStatus(db:DatabaseExecutor,id:string,status:'active'|'disabled'){const q=await db.query<OperatorRow>('UPDATE operations.operators SET status=$2,updated_at=now() WHERE id=$1 RETURNING *',[id,status]);return q.rows[0]?op(q.rows[0]):null;}
 async countOperators(db:DatabaseExecutor){const q=await db.query<CountRow>('SELECT count(*)::text AS count FROM operations.operators');return Number(q.rows[0]?.count??0);}
 async findRoleById(db:DatabaseExecutor,id:string,lock=false){const q=await db.query<RoleRow>(`SELECT * FROM operations.roles WHERE id=$1${lock?' FOR UPDATE':''}`,[id]);return q.rows[0]?role(q.rows[0]):null;}
 async findRoleByCode(db:DatabaseExecutor,code:string,lock=false){if(lock&&code==='super_admin')await this.lockBootstrap(db);const q=await db.query<RoleRow>(`SELECT * FROM operations.roles WHERE code=$1${lock?' FOR UPDATE':''}`,[code]);return q.rows[0]?role(q.rows[0]):null;}
 async listRoles(db:DatabaseExecutor,i:{page:number;pageSize:number;status?:'active'|'disabled'|undefined}):Promise<Page<RoleRecord>>{const v:unknown[]=[];const where=i.status?(v.push(i.status),`WHERE status=$${v.length}`):'';v.push(i.pageSize,(i.page-1)*i.pageSize);const q=await db.query<RoleRow>(`SELECT *, count(*) OVER()::int AS total FROM operations.roles ${where} ORDER BY created_at DESC,id ASC LIMIT $${v.length-1} OFFSET $${v.length}`,v);return{items:q.rows.map(role),total:Number(q.rows[0]?.total??0)};}
 async createRole(db:DatabaseExecutor,i:{id:string;code:string;name:string;description?:string|null|undefined}){const q=await db.query<RoleRow>('INSERT INTO operations.roles(id,code,name,description) VALUES($1,$2,$3,$4) RETURNING *',[i.id,i.code,i.name,i.description??null]);return role(q.rows[0]!);}
 async updateRole(db:DatabaseExecutor,id:string,i:{name?:string|undefined;description?:string|null|undefined;status?:'active'|'disabled'|undefined}){const q=await db.query<RoleRow>('UPDATE operations.roles SET name=COALESCE($2,name),description=CASE WHEN $3::boolean THEN $4 ELSE description END,status=COALESCE($5,status),updated_at=now() WHERE id=$1 RETURNING *',[id,i.name??null,Object.prototype.hasOwnProperty.call(i,'description'),i.description??null,i.status??null]);return q.rows[0]?role(q.rows[0]):null;}
 async listAssignedRoles(db:DatabaseExecutor,operatorId:string):Promise<readonly AssignedRoleRecord[]>{const q=await db.query<RoleRow>('SELECT r.*,orx.created_at AS assigned_at FROM operations.operator_roles orx JOIN operations.roles r ON r.id=orx.role_id WHERE orx.operator_id=$1 ORDER BY r.code ASC',[operatorId]);return q.rows.map(r=>({...role(r),assignedAt:r.assigned_at!}));}
 async addOperatorRole(db:DatabaseExecutor,operatorId:string,roleId:string){const q=await db.query('INSERT INTO operations.operator_roles(operator_id,role_id) VALUES($1,$2) ON CONFLICT DO NOTHING RETURNING operator_id',[operatorId,roleId]);return q.rowCount===1;}
 async removeOperatorRole(db:DatabaseExecutor,operatorId:string,roleId:string){const q=await db.query('DELETE FROM operations.operator_roles WHERE operator_id=$1 AND role_id=$2 RETURNING operator_id',[operatorId,roleId]);return q.rowCount===1;}
 async hasOperatorRole(db:DatabaseExecutor,operatorId:string,roleId:string){const q=await db.query('SELECT 1 FROM operations.operator_roles WHERE operator_id=$1 AND role_id=$2',[operatorId,roleId]);return q.rowCount===1;}
 async countActiveOperatorsWithRole(db:DatabaseExecutor,roleId:string){const q=await db.query<CountRow>('SELECT count(*)::text AS count FROM operations.operator_roles x JOIN operations.operators o ON o.id=x.operator_id WHERE x.role_id=$1 AND o.status=\'active\'',[roleId]);return Number(q.rows[0]?.count??0);}
 async listRolePermissions(db:DatabaseExecutor,roleId:string){const q=await db.query<PermissionRow>('SELECT permission_key FROM operations.role_permissions WHERE role_id=$1 ORDER BY permission_key ASC',[roleId]);return q.rows.map(r=>r.permission_key);}
 async replaceRolePermissions(db:DatabaseExecutor,roleId:string,keys:readonly string[]){const current=await this.listRolePermissions(db,roleId);const wanted=new Set(keys);const old=new Set(current);const added=keys.filter(k=>!old.has(k));const removed=current.filter(k=>!wanted.has(k));if(removed.length)await db.query('DELETE FROM operations.role_permissions WHERE role_id=$1 AND permission_key=ANY($2::text[])',[roleId,removed]);if(added.length)await db.query('INSERT INTO operations.role_permissions(role_id,permission_key) SELECT $1,x FROM unnest($2::text[]) x ON CONFLICT DO NOTHING',[roleId,added]);return{added,removed};}
 async getEffectivePermissions(db:DatabaseExecutor,operatorId:string){const q=await db.query<PermissionRow>('SELECT DISTINCT rp.permission_key FROM operations.operator_roles x JOIN operations.roles r ON r.id=x.role_id AND r.status=\'active\' JOIN operations.role_permissions rp ON rp.role_id=r.id WHERE x.operator_id=$1 ORDER BY rp.permission_key ASC',[operatorId]);return q.rows.map(r=>r.permission_key);}
 async insertAudit(db:DatabaseExecutor,i:{id:string;operatorId:string;actionKey:string;targetDomain?:string|undefined;targetType?:string|undefined;targetId?:string|undefined;requestId?:string|undefined;ipAddress?:string|undefined;details?:Readonly<Record<string,unknown>>|undefined}){const q=await db.query<AuditRow>('INSERT INTO operations.operator_audit_logs(id,operator_id,action_key,target_domain,target_type,target_id,request_id,ip_address,details) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) RETURNING *',[i.id,i.operatorId,i.actionKey,i.targetDomain??null,i.targetType??null,i.targetId??null,i.requestId??null,i.ipAddress??null,JSON.stringify(i.details??{})]);return audit(q.rows[0]!);}
 async findAudit(db:DatabaseExecutor,id:string){const q=await db.query<AuditRow>('SELECT * FROM operations.operator_audit_logs WHERE id=$1',[id]);return q.rows[0]?audit(q.rows[0]):null;}
 async listAudits(db:DatabaseExecutor,i:{operatorId?:string|undefined;actionKey?:string|undefined;targetDomain?:string|undefined;targetType?:string|undefined;targetId?:string|undefined;requestId?:string|undefined;createdFrom?:Date|undefined;createdTo?:Date|undefined;cursor?:string|undefined;limit:number}):Promise<AuditPage>{const w:string[]=[];const v:unknown[]=[];const add=(sql:string,val:unknown)=>{v.push(val);w.push(sql.replace('?',`$${v.length}`));};if(i.operatorId)add('operator_id=?',i.operatorId);if(i.actionKey)add('action_key=?',i.actionKey);if(i.targetDomain)add('target_domain=?',i.targetDomain);if(i.targetType)add('target_type=?',i.targetType);if(i.targetId)add('target_id=?',i.targetId);if(i.requestId)add('request_id=?',i.requestId);if(i.createdFrom)add('created_at>=?',i.createdFrom);if(i.createdTo)add('created_at<=?',i.createdTo);if(i.cursor){const [at,id]=Buffer.from(i.cursor,'base64url').toString('utf8').split('|');v.push(at,id);w.push(`(created_at,id)<($${v.length-1}::timestamptz,$${v.length}::uuid)`);}v.push(i.limit+1);const q=await db.query<AuditRow>(`SELECT * FROM operations.operator_audit_logs${w.length?' WHERE '+w.join(' AND '):''} ORDER BY created_at DESC,id DESC LIMIT $${v.length}`,v);const more=q.rows.length>i.limit;const rows=q.rows.slice(0,i.limit).map(audit);const last=rows.at(-1);return{items:rows,nextCursor:more&&last?Buffer.from(`${last.createdAt.toISOString()}|${last.id}`).toString('base64url'):null};}
}
