import pg from 'pg';
import pino from 'pino';
import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import { asExecutor,createPgPool } from '../../src/database/pool.js';
import { TransactionManager } from '../../src/database/transaction-manager.js';
import { buildApp } from '../../src/bootstrap/build-app.js';
import type { AuthenticationProvider } from '../../src/auth/authentication-provider.js';
import { createTestDatabase,type TestDatabase } from '../support/test-database.js';
import { buildOperationsModule } from '../../src/modules/operations/http/composition.js';
import { OperationsService } from '../../src/modules/operations/application/services/index.js';
import { PostgresOperationsRepository } from '../../src/modules/operations/infrastructure/index.js';
import { buildPlatformModule } from '../../src/modules/platform/http/composition.js';
import { registerPlatformManagementRoutes } from '../../src/modules/platform/http/management-routes.js';
import { parseUserPublicId,type IdentityPublicQueries } from '../../src/modules/identity/public/index.js';

const adminUrl=process.env.ADMIN_DATABASE_URL;const integration=adminUrl?describe:describe.skip;
// ADR-023 统一信封：HTTP 一律 200，顶层 code 权威，成功载荷在 data 内。
const envelope=(response:{json():unknown})=>response.json() as {code:string;data:Record<string,unknown>;error?:{message:string;details?:unknown};request_id:string};
const success=(response:{json():unknown}):Record<string,unknown>=>{const body=envelope(response);expect(body.code).toBe('OK');return body.data;};
const businessCode=(response:{json():unknown}):string=>envelope(response).code;
integration('Operations HTTP and Platform management integration',()=>{
 let database:TestDatabase;let pool:pg.Pool;const logger=pino({level:'silent'});const active=new Set<string>();
 const identity:IdentityPublicQueries={async getIdentityAccountStatus(id){return active.has(id)?'active':null;},async isIdentityActive(id){return active.has(id);},async getIdentitySummary(id){return active.has(id)?{userPublicId:parseUserPublicId(id),status:'active'}:null;}};
 const newSubject=()=>{const id=crypto.randomUUID();active.add(id);return id;};
 const authentication:AuthenticationProvider={async authenticate(request){const id=request.headers['x-test-subject'];return typeof id==='string'?{subjectId:parseUserPublicId(id)}:null;}};
 beforeAll(async()=>{database=await createTestDatabase(adminUrl!);pool=createPgPool({url:database.url,poolMin:0,poolMax:8,connectionTimeoutMs:2_000,idleTimeoutMs:2_000},logger);},120_000);
 afterAll(async()=>{if(pool)await pool.end();if(database)await database.dispose();},30_000);
 it('enforces authentication, exact RBAC, strict DTO and exposes /me permissions',async()=>{const executor=asExecutor(pool);const operations=buildOperationsModule({executor,transactionManager:new TransactionManager(pool,logger),identity,authentication});const rootSubject=newSubject();const root=await operations.service.bootstrap(rootSubject,'Root');const app=buildApp({logger,database:executor});await operations.registerHttp(app);
  const unauthenticated=await app.inject({method:'GET',url:'/api/v1/admin/operations/me'});expect(unauthenticated.statusCode).toBe(200);expect(businessCode(unauthenticated)).toBe('UNAUTHENTICATED');
  const me=await app.inject({method:'GET',url:'/api/v1/admin/operations/me',headers:{'x-test-subject':rootSubject}});expect(me.statusCode).toBe(200);expect(businessCode(me)).toBe('OK');expect(((success(me).operator as Record<string,unknown>).permissions as Array<unknown>)).toHaveLength(68);
  const weakSubject=newSubject();await operations.service.createOperator({operatorId:root.operator.id,authSubjectId:rootSubject},{authSubjectId:weakSubject,displayName:'No Role'});
  const weakList=await app.inject({method:'GET',url:'/api/v1/admin/operations/operators',headers:{'x-test-subject':weakSubject}});expect(weakList.statusCode).toBe(200);expect(businessCode(weakList)).toBe('FORBIDDEN');
  const weakRead=await app.inject({method:'GET',url:`/api/v1/admin/operations/operators/${root.operator.id}`,headers:{'x-test-subject':weakSubject}});expect(weakRead.statusCode).toBe(200);expect(businessCode(weakRead)).toBe('FORBIDDEN');
  const invalid=await app.inject({method:'POST',url:'/api/v1/admin/operations/roles',headers:{'x-test-subject':rootSubject},payload:{code:'strict_role',name:'Strict',unexpected:true}});expect(invalid.statusCode).toBe(200);expect(businessCode(invalid)).toBe('INVALID_ARGUMENT');
  await app.close();
 });
 it('authorizes a real Platform management mutation, hides internal ids, and records success-only audit context',async()=>{const executor=asExecutor(pool);const tx=new TransactionManager(pool,logger);const operations=buildOperationsModule({executor,transactionManager:tx,identity,authentication});const root=(await operations.service.listOperators({page:1,pageSize:10})).items.find(o=>o.displayName==='Root')!;const platform=buildPlatformModule({executor,transactionManager:tx});const app=buildApp({logger,database:executor});await registerPlatformManagementRoutes(app,{executor,authentication,authorizer:operations.service,audit:operations.service,management:platform.managementService!,featureFlags:platform.featureFlagUseCases,runtimeConfigs:platform.runtimeConfigUseCases,appVersions:platform.appVersionUseCases,announcements:platform.announcementUseCases,regions:platform.regionUseCases});
  const deniedSubject=newSubject();await operations.service.createOperator({operatorId:root.id,authSubjectId:root.authSubjectId},{authSubjectId:deniedSubject,displayName:'Denied'});const denied=await app.inject({method:'POST',url:'/api/v1/admin/platform/feature-flags',headers:{'x-test-subject':deniedSubject},payload:{key:'ops_test_flag',name:'Ops Test Flag'}});expect(denied.statusCode).toBe(200);expect(businessCode(denied)).toBe('FORBIDDEN');
  const deniedAudits=await operations.service.listAudits({actionKey:'platform.feature_flags.write',limit:50});expect(deniedAudits.items).toHaveLength(0);
  const ok=await app.inject({method:'POST',url:'/api/v1/admin/platform/feature-flags',headers:{'x-test-subject':root.authSubjectId},payload:{key:'ops_test_flag',name:'Ops Test Flag'}});expect(ok.statusCode).toBe(200);expect(businessCode(ok)).toBe('OK');expect((success(ok).feature_flag as Record<string,unknown>).id).toBeUndefined();
  const audits=await operations.service.listAudits({actionKey:'platform.feature_flags.write',operatorId:root.id,limit:50});expect(audits.items).toHaveLength(1);expect(audits.items[0]?.details).toMatchObject({key:'ops_test_flag'});expect(audits.items[0]?.requestId).toBeTruthy();expect(audits.items[0]?.ipAddress).toBeTruthy();
  await app.close();
 });
 it('maps all five Platform management resources to separate exact read/write permissions',async()=>{const executor=asExecutor(pool);const tx=new TransactionManager(pool,logger);const operations=buildOperationsModule({executor,transactionManager:tx,identity,authentication});const root=(await operations.service.listOperators({page:1,pageSize:20})).items.find(o=>o.displayName==='Root')!;const actor={operatorId:root.id,authSubjectId:root.authSubjectId};const subject=newSubject();const operator=await operations.service.createOperator(actor,{authSubjectId:subject,displayName:'Platform Scoped'});const role=await operations.service.createRole(actor,{code:'platform_scoped',name:'Platform Scoped'});await operations.service.setRolePermissions(actor,role.id,['platform.feature_flags.read','platform.runtime_configs.read','platform.app_versions.read','platform.announcements.read','platform.regions.read']);await operations.service.assignRole(actor,operator.id,role.id);
  const platform=buildPlatformModule({executor,transactionManager:tx});const app=buildApp({logger,database:executor});await registerPlatformManagementRoutes(app,{executor,authentication,authorizer:operations.service,audit:operations.service,management:platform.managementService!,featureFlags:platform.featureFlagUseCases,runtimeConfigs:platform.runtimeConfigUseCases,appVersions:platform.appVersionUseCases,announcements:platform.announcementUseCases,regions:platform.regionUseCases});const h={'x-test-subject':subject};
  for(const url of ['/api/v1/admin/platform/feature-flags','/api/v1/admin/platform/runtime-configs','/api/v1/admin/platform/app-versions','/api/v1/admin/platform/announcements','/api/v1/admin/platform/regions']){const read=await app.inject({method:'GET',url,headers:h});expect(read.statusCode).toBe(200);expect(businessCode(read)).toBe('OK');}
  const deniedWrites=[
   app.inject({method:'POST',url:'/api/v1/admin/platform/feature-flags',headers:h,payload:{key:'scoped_flag',name:'Scoped'}}),
   app.inject({method:'PUT',url:'/api/v1/admin/platform/runtime-configs/scoped_config',headers:h,payload:{value_type:'string',value:'x'}}),
   app.inject({method:'POST',url:'/api/v1/admin/platform/app-versions',headers:h,payload:{client_platform:'android',version:'9.9.1',build_number:99901}}),
   app.inject({method:'POST',url:'/api/v1/admin/platform/announcements',headers:h,payload:{title:'Scoped',content:'Scoped'}}),
   app.inject({method:'POST',url:'/api/v1/admin/platform/regions',headers:h,payload:{code:'ZZ',name:'Scoped',default_locale:'en-US',timezone:'UTC'}}),
  ];const deniedResults=await Promise.all(deniedWrites);expect(deniedResults.map(r=>r.statusCode)).toEqual([200,200,200,200,200]);expect(deniedResults.map(r=>businessCode(r))).toEqual(['FORBIDDEN','FORBIDDEN','FORBIDDEN','FORBIDDEN','FORBIDDEN']);
  await operations.service.setRolePermissions(actor,role.id,['platform.feature_flags.write','platform.runtime_configs.write','platform.app_versions.write','platform.announcements.write','platform.regions.write']);
  for(const url of ['/api/v1/admin/platform/feature-flags','/api/v1/admin/platform/runtime-configs','/api/v1/admin/platform/app-versions','/api/v1/admin/platform/announcements','/api/v1/admin/platform/regions']){const read=await app.inject({method:'GET',url,headers:h});expect(read.statusCode).toBe(200);expect(businessCode(read)).toBe('FORBIDDEN');}
  const writeFlag=await app.inject({method:'POST',url:'/api/v1/admin/platform/feature-flags',headers:h,payload:{key:'scoped_flag',name:'Scoped'}});expect(writeFlag.statusCode).toBe(200);expect(businessCode(writeFlag)).toBe('OK');
  const writeVersion=await app.inject({method:'POST',url:'/api/v1/admin/platform/app-versions',headers:h,payload:{client_platform:'android',version:'9.9.1',build_number:99901}});expect(writeVersion.statusCode).toBe(200);expect(businessCode(writeVersion)).toBe('OK');
  const writeAnnouncement=await app.inject({method:'POST',url:'/api/v1/admin/platform/announcements',headers:h,payload:{title:'Scoped',content:'Scoped'}});expect(writeAnnouncement.statusCode).toBe(200);expect(businessCode(writeAnnouncement)).toBe('OK');
  const writeRegion=await app.inject({method:'POST',url:'/api/v1/admin/platform/regions',headers:h,payload:{code:'ZZ',name:'Scoped',default_locale:'en-US',timezone:'UTC'}});expect(writeRegion.statusCode).toBe(200);expect(businessCode(writeRegion)).toBe('OK');
  const writeConfig=await app.inject({method:'PUT',url:'/api/v1/admin/platform/runtime-configs/scoped_config',headers:h,payload:{value_type:'string',value:'x'}});expect(writeConfig.statusCode).toBe(200);expect(businessCode(writeConfig)).not.toBe('FORBIDDEN');
  await app.close();
 });
 it('returns an explicit audit ambiguity error if Platform commits but Operations audit persistence fails',async()=>{const executor=asExecutor(pool);const tx=new TransactionManager(pool,logger);const base=new PostgresOperationsRepository();const failingRepo=new Proxy(base,{get(target,prop,receiver){if(prop==='insertAudit')return async()=>{throw new Error('audit unavailable');};return Reflect.get(target,prop,receiver);}}) as PostgresOperationsRepository;const failingOperations=new OperationsService(tx,executor,failingRepo,identity);const root=(await failingOperations.listOperators({page:1,pageSize:20})).items.find(o=>o.displayName==='Root')!;const platform=buildPlatformModule({executor,transactionManager:tx});const app=buildApp({logger,database:executor});await registerPlatformManagementRoutes(app,{executor,authentication,authorizer:failingOperations,audit:failingOperations,management:platform.managementService!,featureFlags:platform.featureFlagUseCases,runtimeConfigs:platform.runtimeConfigUseCases,appVersions:platform.appVersionUseCases,announcements:platform.announcementUseCases,regions:platform.regionUseCases});
  const response=await app.inject({method:'POST',url:'/api/v1/admin/platform/feature-flags',headers:{'x-test-subject':root.authSubjectId},payload:{key:'audit_gap_flag',name:'Audit Gap'}});expect(response.statusCode).toBe(200);expect(businessCode(response)).toBe('OPERATOR_AUDIT_PERSISTENCE_FAILED');expect(envelope(response).error?.message).toBe('Internal server error');const flags=await platform.featureFlagUseCases.listFeatureFlagsForManagement(executor);expect(flags.some(f=>f.key==='audit_gap_flag')).toBe(true);const audits=await new OperationsService(tx,executor,base,identity).listAudits({actionKey:'platform.feature_flags.write',limit:100});expect(audits.items.some(a=>a.details.key==='audit_gap_flag')).toBe(false);await app.close();
 });
});
