import pg from 'pg';
import pino from 'pino';
import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import { asExecutor,createPgPool } from '../../src/database/pool.js';
import { TransactionManager } from '../../src/database/transaction-manager.js';
import { createTestDatabase,type TestDatabase } from '../support/test-database.js';
import { OperationsService } from '../../src/modules/operations/application/services/index.js';
import { PostgresOperationsRepository } from '../../src/modules/operations/infrastructure/index.js';
import { parseUserPublicId,type IdentityPublicQueries } from '../../src/modules/identity/public/index.js';

const adminUrl=process.env.ADMIN_DATABASE_URL;const integration=adminUrl?describe:describe.skip;const logger=pino({level:'silent'});
integration('Operations security/race invariants',()=>{
 let database:TestDatabase;let pool:pg.Pool;const active=new Set<string>();
 const identity:IdentityPublicQueries={async getIdentityAccountStatus(id){return active.has(id)?'active':null;},async isIdentityActive(id){return active.has(id);},async getIdentitySummary(id){return active.has(id)?{userPublicId:parseUserPublicId(id),status:'active'}:null;}};
 const subject=()=>{const id=crypto.randomUUID();active.add(id);return id;};
 beforeAll(async()=>{database=await createTestDatabase(adminUrl!);pool=createPgPool({url:database.url,poolMin:0,poolMax:12,connectionTimeoutMs:3_000,idleTimeoutMs:3_000},logger);},120_000);
 afterAll(async()=>{if(pool)await pool.end();if(database)await database.dispose();},30_000);
 const service=()=>new OperationsService(new TransactionManager(pool,logger),asExecutor(pool),new PostgresOperationsRepository(),identity);
 it('concurrent bootstrap produces exactly one root operator and one protected super_admin',async()=>{const a=service(),b=service();const results=await Promise.allSettled([a.bootstrap(subject(),'Root A'),b.bootstrap(subject(),'Root B')]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(results.filter(x=>x.status==='rejected')).toHaveLength(1);const operators=await a.listOperators({page:1,pageSize:20});const roles=await a.listRoles({page:1,pageSize:20});expect(operators.total).toBe(1);expect(roles.items.filter(r=>r.code==='super_admin')).toHaveLength(1);});
 it('concurrent permission replacement serializes to one complete requested set, never a mixed set',async()=>{const s=service();const root=(await s.listOperators({page:1,pageSize:10})).items[0]!;const actor={operatorId:root.id,authSubjectId:root.authSubjectId};const role=await s.createRole(actor,{code:'race_permissions',name:'Race Permissions'});const setA=['operations.operators.read','operations.roles.read'] as const;const setB=['operations.operators.read','operations.audit_logs.read'] as const;await Promise.all([s.setRolePermissions(actor,role.id,setA),s.setRolePermissions(actor,role.id,setB)]);const final=await s.listRolePermissions(role.id);expect([setA.slice().sort(),setB.slice().sort()]).toContainEqual([...final].sort());});
 it('rejects wildcard/unknown permission injection before persistence',async()=>{const s=service();const root=(await s.listOperators({page:1,pageSize:10})).items[0]!;const actor={operatorId:root.id,authSubjectId:root.authSubjectId};const role=await s.createRole(actor,{code:'injection_role',name:'Injection'});await expect(s.setRolePermissions(actor,role.id,['platform.*'])).rejects.toMatchObject({code:'INVALID_PERMISSION'});await expect(s.setRolePermissions(actor,role.id,['content.lessons.read'])).rejects.toMatchObject({code:'INVALID_PERMISSION'});expect(await s.listRolePermissions(role.id)).toEqual([]);});
 it('rejects sensitive audit details and persists no secret-bearing audit row',async()=>{const s=service();const root=(await s.listOperators({page:1,pageSize:10})).items[0]!;const operator={operatorId:root.id,authSubjectId:root.authSubjectId};const before=(await s.listAudits({operatorId:root.id,limit:100})).items.length;await expect(s.recordSuccessfulAction({operator,actionKey:'operations.roles.update',details:{authorization:'Bearer secret-token'}})).rejects.toMatchObject({code:'INVALID_ARGUMENT'});const after=(await s.listAudits({operatorId:root.id,limit:100})).items.length;expect(after).toBe(before);});
 it('operator and role disable decisions take effect on the next authorization without cache staleness',async()=>{const s=service();const root=(await s.listOperators({page:1,pageSize:10})).items[0]!;const actor={operatorId:root.id,authSubjectId:root.authSubjectId};const authSubject=subject();const operator=await s.createOperator(actor,{authSubjectId:authSubject,displayName:'Race Worker'});const role=await s.createRole(actor,{code:'race_reader',name:'Race Reader'});await s.setRolePermissions(actor,role.id,['operations.operators.read']);await s.assignRole(actor,operator.id,role.id);const auth={subjectId:parseUserPublicId(authSubject)};await expect(s.requirePermission(auth,'operations.operators.read')).resolves.toBeTruthy();await s.setRoleStatus(actor,role.id,'disabled');await expect(s.requirePermission(auth,'operations.operators.read')).rejects.toMatchObject({code:'FORBIDDEN'});await s.setRoleStatus(actor,role.id,'active');await expect(s.requirePermission(auth,'operations.operators.read')).resolves.toBeTruthy();await s.setOperatorStatus(actor,operator.id,'disabled');await expect(s.requirePermission(auth,'operations.operators.read')).rejects.toMatchObject({code:'OPERATOR_DISABLED'});});
});
