import { buildApp } from './bootstrap/build-app.js';
import { installShutdown } from './bootstrap/shutdown.js';
import { configSummary,loadConfig } from './config/env.js';
import { asExecutor,createPgPool } from './database/pool.js';
import { TransactionManager } from './database/transaction-manager.js';
import { createLogger } from './logging/logger.js';
import { identityModule } from './modules/identity/index.js';
import { createIdentityHttpDependencies } from './modules/identity/http/composition.js';
import { createIdentityRepositories } from './modules/identity/infrastructure/index.js';
import { createIdentityPublicQuery } from './modules/identity/application/services/identity-public-query.js';
import { ConsoleOtpDeliveryProvider,UnavailableFacebookCredentialVerifier,UnavailableOtpDeliveryProvider } from './modules/identity/application/services/index.js';
import { buildPlatformModule } from './modules/platform/http/composition.js';
import { platformModule } from './modules/platform/index.js';
import { registerPlatformManagementRoutes } from './modules/platform/http/management-routes.js';
import { buildOperationsModule } from './modules/operations/http/composition.js';
const config=loadConfig();const logger=createLogger(config.logLevel);const pool=createPgPool(config.database,logger);const executor=asExecutor(pool);const transactionManager=new TransactionManager(pool,logger);const readinessState={isShuttingDown:false};const app=buildApp({logger,database:executor,readinessState});
const identityDependencies=createIdentityHttpDependencies({transactionManager,repositories:createIdentityRepositories,executor,otpHmacSecret:config.identity.otpHmacSecret??'',jwtHmacSecret:config.identity.jwtHmacSecret??'',jwtIssuer:config.identity.jwtIssuer,jwtAudience:config.identity.jwtAudience,facebookVerifier:new UnavailableFacebookCredentialVerifier(),otpDelivery:config.identity.otpProvider==='console'?new ConsoleOtpDeliveryProvider({info:(message,fields)=>logger.info(fields,message)}):new UnavailableOtpDeliveryProvider()});await identityModule.registerHttp(app,identityDependencies);
const identityPublic=createIdentityPublicQuery(createIdentityRepositories,executor);const operations=buildOperationsModule({executor,transactionManager,identity:identityPublic,authentication:identityDependencies.authentication});await operations.registerHttp(app);
const platform=buildPlatformModule({executor,transactionManager});await platformModule.registerHttp(app,{executor,featureFlagUseCases:platform.featureFlagUseCases,appVersionUseCases:platform.appVersionUseCases,announcementUseCases:platform.announcementUseCases,regionUseCases:platform.regionUseCases});
if(platform.managementService)await registerPlatformManagementRoutes(app,{executor,authentication:identityDependencies.authentication,authorizer:operations.service,audit:operations.service,management:platform.managementService,featureFlags:platform.featureFlagUseCases,runtimeConfigs:platform.runtimeConfigUseCases,appVersions:platform.appVersionUseCases,announcements:platform.announcementUseCases,regions:platform.regionUseCases});
logger.info({config:configSummary(config)},'Starting ZH-LAO backend');await app.listen({host:config.host,port:config.port});installShutdown({logger,timeoutMs:config.shutdownTimeoutMs,markShuttingDown:()=>{readinessState.isShuttingDown=true;},close:async()=>{await app.close();await pool.end();}});
