import { buildWorker } from './bootstrap/build-worker.js';
import { installShutdown } from './bootstrap/shutdown.js';
import { configSummary, loadConfig } from './config/env.js';
import { asExecutor, createPgPool } from './database/pool.js';
import { createLogger } from './logging/logger.js';
import { EventHandlerRegistry } from './events/handler-registry.js';
import { PostgresContentAudioSourceReader } from './modules/content/infrastructure/postgres-content-audio-source-reader.js';
import { ContentPublicQueryService } from './modules/content/public/content-public-queries.js';
import { AudioRequirementSyncService } from './modules/audio/application/audio-requirement-sync-service.js';
import { ContentAudioRequirementHandler } from './modules/audio/worker/content-audio-requirement-handler.js';

const config = loadConfig();
const logger = createLogger(config.logLevel);
const pool = createPgPool(config.database, logger);
const database=asExecutor(pool); const handlers=new EventHandlerRegistry();
handlers.register('content.audio_requirement_changed',new ContentAudioRequirementHandler(new AudioRequirementSyncService(database,new ContentPublicQueryService(new PostgresContentAudioSourceReader(database)))));
const worker = buildWorker(config, database, logger, handlers);
logger.info({ config: configSummary(config) }, 'Starting ZH-LAO worker');
worker.start();
installShutdown({ logger, timeoutMs: config.shutdownTimeoutMs, close: async () => { await worker.stop(); await pool.end(); } });
