import { randomUUID } from 'node:crypto';
import { AppError } from '../../../../errors/app-error.js';
import type { BusinessStatusCode } from '../../../../errors/business-codes.js';
import type { AuthContext } from '../../../../auth/auth-context.js';
import type { DatabaseExecutor } from '../../../../database/executor.js';
import type { TransactionManager } from '../../../../database/transaction-manager.js';
import type { IdentityPublicQueries, UserPublicId } from '../../../identity/public/index.js';
import type { AdminCredentialOperations } from '../../../identity/public/index.js';
import type { OperationsRepository } from '../ports/index.js';
import { OPERATOR_PERMISSION_CATALOG,isOperatorPermissionKey,type AuthorizedOperatorContext,type OperatorPermissionKey,type OperationsAuditRecorder,type OperationsAuthorizer,type OperationsBatchWorkerBoundary,type OperationsOperatorResolver,type OperationsTransactionalAuditBoundary,type OperatorSummary } from '../../public/index.js';

const err=(code:BusinessStatusCode,message:string,httpStatus:number)=>new AppError({code,message,httpStatus});
const pgCode=(e:unknown)=>typeof e==='object'&&e!==null&&'code' in e?String((e as {code?:unknown}).code):undefined;
const name=(s:string)=>{const v=s.trim();if(!v||v.length>100)throw err('INVALID_ARGUMENT','Invalid display/name',400);return v;};
const safe=(details:Readonly<Record<string,unknown>>={})=>{const text=JSON.stringify(details);if(text.length>8192)throw err('INVALID_ARGUMENT','Audit details too large',400);if(/password|token|authorization|secret|card|payment_credential/i.test(text))throw err('INVALID_ARGUMENT','Sensitive audit details are forbidden',400);return details;};

export class OperationsService implements OperationsAuthorizer,OperationsOperatorResolver,OperationsAuditRecorder,OperationsTransactionalAuditBoundary,OperationsBatchWorkerBoundary{
 constructor(private readonly tx:TransactionManager,private readonly db:DatabaseExecutor,private readonly repo:OperationsRepository,private readonly identity:IdentityPublicQueries,private readonly credentials?:AdminCredentialOperations){}
 private async requireActiveIdentity(subjectId:string){const s=await this.identity.getIdentitySummary(subjectId as UserPublicId);if(!s)throw err('OPERATOR_AUTH_SUBJECT_NOT_FOUND','Identity subject not found',400);if(s.status!=='active')throw err('OPERATOR_AUTH_SUBJECT_INACTIVE','Identity subject is not active',409);}
 async resolveCurrentOperator(auth:AuthContext):Promise<OperatorSummary>{const o=await this.repo.findOperatorByAuthSubjectId(this.db,auth.subjectId);if(!o)throw err('OPERATOR_ACCESS_DENIED','No operator mapping',403);if(o.status!=='active')throw err('OPERATOR_DISABLED','Operator is disabled',403);return{operatorId:o.id,authSubjectId:o.authSubjectId,displayName:o.displayName,status:o.status};}
 async requirePermission(auth:AuthContext,p:OperatorPermissionKey):Promise<AuthorizedOperatorContext>{const snapshot=await this.repo.getAuthorizationSnapshot(this.db,auth.subjectId,p);if(!snapshot)throw err('OPERATOR_ACCESS_DENIED','No operator mapping',403);const o=snapshot.operator;if(o.status!=='active')throw err('OPERATOR_DISABLED','Operator is disabled',403);if(!snapshot.hasPermission)throw err('FORBIDDEN','Permission denied',403);return{operatorId:o.id,authSubjectId:o.authSubjectId};}
 async getCurrentOperator(auth:AuthContext){const operator=await this.resolveCurrentOperator(auth);const roles=await this.repo.listAssignedRoles(this.db,operator.operatorId);const permissions=await this.repo.getEffectivePermissions(this.db,operator.operatorId);return{operator,roles:roles.filter(r=>r.status==='active'),permissions:permissions.filter(isOperatorPermissionKey).sort()};}
 async recordSuccessfulAction(i:{operator:AuthorizedOperatorContext;actionKey:string;target?:{domain:string;type:string;id?:string|undefined}|undefined;requestContext?:{requestId?:string|undefined;ipAddress?:string|undefined}|undefined;details?:Readonly<Record<string,unknown>>|undefined}){const details=safe(i.details);try{await this.repo.insertAudit(this.db,{id:randomUUID(),operatorId:i.operator.operatorId,actionKey:i.actionKey,targetDomain:i.target?.domain,targetType:i.target?.type,targetId:i.target?.id,requestId:i.requestContext?.requestId,ipAddress:i.requestContext?.ipAddress,details});}catch(cause){throw new AppError({code:'OPERATOR_AUDIT_PERSISTENCE_FAILED',message:'Operator action audit could not be persisted',httpStatus:500,expose:false,cause});}}
 async requireOperatorPermissionInTransaction(db:DatabaseExecutor,operatorId:string,permission:OperatorPermissionKey):Promise<void>{const operator=await this.repo.findOperatorById(db,operatorId);if(!operator)throw err('OPERATOR_ACCESS_DENIED','No operator mapping',403);if(operator.status!=='active')throw err('OPERATOR_DISABLED','Operator is disabled',403);const permissions=await this.repo.getEffectivePermissions(db,operatorId);if(!permissions.includes(permission))throw err('FORBIDDEN','Permission denied',403);}
 async recordSuccessfulActionInTransaction(db:DatabaseExecutor,input:{operatorId:string;actionKey:string;target:{domain:'content';type:'course'|'lesson';id:string};requestContext?:{requestId?:string;ipAddress?:string};details?:Readonly<Record<string,unknown>>}):Promise<void>{await this.repo.insertAudit(db,{id:randomUUID(),operatorId:input.operatorId,actionKey:input.actionKey,targetDomain:input.target.domain,targetType:input.target.type,targetId:input.target.id,requestId:input.requestContext?.requestId,ipAddress:input.requestContext?.ipAddress,details:safe(input.details)});}
 async recordBatchSuccessfulActionInTransaction(db:DatabaseExecutor,input:{operatorId:string;actionKey:string;contentId:string;batchTaskId:string}):Promise<void>{await this.repo.insertAudit(db,{id:randomUUID(),operatorId:input.operatorId,actionKey:input.actionKey,targetDomain:'content',targetType:'lo_letter',targetId:input.contentId,details:{batch_task_id:input.batchTaskId}});}
 private localAudit(db:DatabaseExecutor,actor:AuthorizedOperatorContext,actionKey:string,target?:{domain:string;type:string;id?:string|undefined},details?:Readonly<Record<string,unknown>>,requestContext?:{requestId?:string|undefined;ipAddress?:string|undefined}){return this.repo.insertAudit(db,{id:randomUUID(),operatorId:actor.operatorId,actionKey,targetDomain:target?.domain,targetType:target?.type,targetId:target?.id,requestId:requestContext?.requestId,ipAddress:requestContext?.ipAddress,details:safe(details)});}
 async listOperators(input:{page:number;pageSize:number;status?:'active'|'disabled'|undefined}){return this.repo.listOperators(this.db,input);}
 async getOperator(id:string){const o=await this.repo.findOperatorById(this.db,id);if(!o)throw err('OPERATOR_NOT_FOUND','Operator not found',404);return o;}
 async createOperator(actor:AuthorizedOperatorContext,input:{authSubjectId:string;displayName:string},ctx?:{requestId?:string;ipAddress?:string}){await this.requireActiveIdentity(input.authSubjectId);try{return await this.tx.run(async db=>{const o=await this.repo.createOperator(db,{id:randomUUID(),authSubjectId:input.authSubjectId,displayName:name(input.displayName)});await this.localAudit(db,actor,'operations.operators.create',{domain:'operations',type:'operator',id:o.id},{auth_subject_id:o.authSubjectId},ctx);return o;});}catch(e){if(pgCode(e)==='23505')throw err('OPERATOR_ALREADY_EXISTS','Identity subject already mapped',409);throw e;}}
 async updateOperator(actor:AuthorizedOperatorContext,id:string,displayName:string,ctx?:{requestId?:string;ipAddress?:string}){return this.tx.run(async db=>{const current=await this.repo.findOperatorById(db,id,true);if(!current)throw err('OPERATOR_NOT_FOUND','Operator not found',404);const nextName=name(displayName);if(current.displayName===nextName)return current;const next=await this.repo.updateOperatorDisplayName(db,id,nextName);await this.localAudit(db,actor,'operations.operators.update',{domain:'operations',type:'operator',id},undefined,ctx);return next!;});}
 async setOperatorStatus(actor:AuthorizedOperatorContext,id:string,status:'active'|'disabled',ctx?:{requestId?:string;ipAddress?:string}){return this.tx.run(async db=>{const superRole=status==='disabled'?await this.repo.findRoleByCode(db,'super_admin',true):null;const current=await this.repo.findOperatorById(db,id,true);if(!current)throw err('OPERATOR_NOT_FOUND','Operator not found',404);if(current.status===status)return current;if(status==='active')await this.requireActiveIdentity(current.authSubjectId);if(status==='disabled'&&superRole&&await this.repo.hasOperatorRole(db,id,superRole.id)){const count=await this.repo.countActiveOperatorsWithRole(db,superRole.id);if(count<=1)throw err('LAST_SUPER_ADMIN_REQUIRED','At least one active super-admin is required',409);}const next=await this.repo.updateOperatorStatus(db,id,status);await this.localAudit(db,actor,`operations.operators.${status==='active'?'enable':'disable'}`,{domain:'operations',type:'operator',id},undefined,ctx);return next!;});}
 async resetOperatorPassword(actor:AuthorizedOperatorContext,id:string,ctx?:{requestId?:string;ipAddress?:string}){
  if(!this.credentials)throw err('INTERNAL_ERROR','Admin credential reset is unavailable',500);
  if(actor.operatorId===id)throw err('OPERATOR_PASSWORD_RESET_NOT_ALLOWED','An operator cannot reset their own password',409);
  return this.tx.run(async db=>{
   const target=await this.repo.findOperatorById(db,id,true);if(!target)throw err('OPERATOR_NOT_FOUND','Operator not found',404);
   if(target.status!=='active')throw err('OPERATOR_PASSWORD_RESET_NOT_ALLOWED','Target operator is not eligible for password reset',409);
   await this.requireActiveIdentity(target.authSubjectId);
   const superRole=await this.repo.findRoleByCode(db,'super_admin',true);
   if(superRole&&await this.repo.hasOperatorRole(db,id,superRole.id)&&!await this.repo.hasOperatorRole(db,actor.operatorId,superRole.id))throw err('OPERATOR_PASSWORD_RESET_NOT_ALLOWED','Only a super-admin can reset another super-admin',409);
   const reset=await this.credentials!.resetPasswordInTransaction(db,target.authSubjectId as UserPublicId);
   await this.localAudit(db,actor,'operations.operators.reset_password',{domain:'operations',type:'operator',id},undefined,ctx);
   return{operator:target,temporaryPassword:reset.temporaryPassword};
  });
 }
 async listRoles(input:{page:number;pageSize:number;status?:'active'|'disabled'|undefined}){return this.repo.listRoles(this.db,input);}
 async getRole(id:string){const r=await this.repo.findRoleById(this.db,id);if(!r)throw err('ROLE_NOT_FOUND','Role not found',404);return r;}
 async createRole(actor:AuthorizedOperatorContext,input:{code:string;name:string;description?:string|null|undefined},ctx?:{requestId?:string;ipAddress?:string}){if(input.code==='super_admin')throw err('SYSTEM_ROLE_PROTECTED','super_admin is bootstrap-reserved',409);if(!/^[a-z][a-z0-9_]{0,49}$/.test(input.code))throw err('INVALID_ARGUMENT','Invalid role code',400);try{return await this.tx.run(async db=>{const r=await this.repo.createRole(db,{id:randomUUID(),code:input.code,name:name(input.name),description:input.description?.trim()||null});await this.localAudit(db,actor,'operations.roles.create',{domain:'operations',type:'role',id:r.id},{code:r.code},ctx);return r;});}catch(e){if(pgCode(e)==='23505')throw err('ROLE_CODE_CONFLICT','Role code already exists',409);throw e;}}
 async updateRole(actor:AuthorizedOperatorContext,id:string,input:{name?:string|undefined;description?:string|null|undefined},ctx?:{requestId?:string;ipAddress?:string}){return this.tx.run(async db=>{const current=await this.repo.findRoleById(db,id,true);if(!current)throw err('ROLE_NOT_FOUND','Role not found',404);const patch:{name?:string;description?:string|null}={};if(input.name!==undefined)patch.name=name(input.name);if(input.description!==undefined)patch.description=input.description?.trim()||null;const same=(patch.name===undefined||patch.name===current.name)&&(patch.description===undefined||patch.description===current.description);if(same)return current;const next=await this.repo.updateRole(db,id,patch);await this.localAudit(db,actor,'operations.roles.update',{domain:'operations',type:'role',id},undefined,ctx);return next!;});}
 async setRoleStatus(actor:AuthorizedOperatorContext,id:string,status:'active'|'disabled',ctx?:{requestId?:string;ipAddress?:string}){return this.tx.run(async db=>{const current=await this.repo.findRoleById(db,id,true);if(!current)throw err('ROLE_NOT_FOUND','Role not found',404);if(current.status===status)return current;if(current.code==='super_admin'&&status==='disabled')throw err('SYSTEM_ROLE_PROTECTED','super_admin cannot be disabled',409);const next=await this.repo.updateRole(db,id,{status});await this.localAudit(db,actor,`operations.roles.${status==='active'?'enable':'disable'}`,{domain:'operations',type:'role',id},undefined,ctx);return next!;});}
 async listAssignedRoles(operatorId:string){await this.getOperator(operatorId);return this.repo.listAssignedRoles(this.db,operatorId);}
 async assignRole(actor:AuthorizedOperatorContext,operatorId:string,roleId:string,ctx?:{requestId?:string;ipAddress?:string}){return this.tx.run(async db=>{const o=await this.repo.findOperatorById(db,operatorId,true);if(!o)throw err('OPERATOR_NOT_FOUND','Operator not found',404);if(o.status!=='active')throw err('OPERATOR_DISABLED','Target operator disabled',409);const r=await this.repo.findRoleById(db,roleId,true);if(!r)throw err('ROLE_NOT_FOUND','Role not found',404);if(r.status!=='active')throw err('ROLE_DISABLED','Role disabled',409);const changed=await this.repo.addOperatorRole(db,operatorId,roleId);if(changed)await this.localAudit(db,actor,'operations.operator_roles.assign',{domain:'operations',type:'operator',id:operatorId},{role_id:roleId},ctx);return changed;});}
 async revokeRole(actor:AuthorizedOperatorContext,operatorId:string,roleId:string,ctx?:{requestId?:string;ipAddress?:string}){return this.tx.run(async db=>{const r=await this.repo.findRoleById(db,roleId,true);if(!r)throw err('ROLE_NOT_FOUND','Role not found',404);if(r.code==='super_admin'&&await this.repo.hasOperatorRole(db,operatorId,roleId)){const count=await this.repo.countActiveOperatorsWithRole(db,roleId);const target=await this.repo.findOperatorById(db,operatorId,true);if(target?.status==='active'&&count<=1)throw err('LAST_SUPER_ADMIN_REQUIRED','At least one active super-admin is required',409);}const changed=await this.repo.removeOperatorRole(db,operatorId,roleId);if(changed)await this.localAudit(db,actor,'operations.operator_roles.revoke',{domain:'operations',type:'operator',id:operatorId},{role_id:roleId},ctx);return changed;});}
 async listPermissionCatalog(){return OPERATOR_PERMISSION_CATALOG;}
 async listRolePermissions(roleId:string){await this.getRole(roleId);return this.repo.listRolePermissions(this.db,roleId);}
 async setRolePermissions(actor:AuthorizedOperatorContext,roleId:string,keys:readonly string[],ctx?:{requestId?:string;ipAddress?:string}){if(new Set(keys).size!==keys.length||keys.some(k=>!isOperatorPermissionKey(k)))throw err('INVALID_PERMISSION','Invalid or duplicate permission',400);return this.tx.run(async db=>{const r=await this.repo.findRoleById(db,roleId,true);if(!r)throw err('ROLE_NOT_FOUND','Role not found',404);if(r.code==='super_admin'&&(keys.length!==OPERATOR_PERMISSION_CATALOG.length||OPERATOR_PERMISSION_CATALOG.some(k=>!keys.includes(k))))throw err('SYSTEM_ROLE_PROTECTED','super_admin must have complete catalog',409);const diff=await this.repo.replaceRolePermissions(db,roleId,keys);if(diff.added.length||diff.removed.length)await this.localAudit(db,actor,'operations.role_permissions.set',{domain:'operations',type:'role',id:roleId},{added:diff.added,removed:diff.removed},ctx);return{permissions:(await this.repo.listRolePermissions(db,roleId)).filter(isOperatorPermissionKey),changed:Boolean(diff.added.length||diff.removed.length)};});}
 async getAudit(id:string){const a=await this.repo.findAudit(this.db,id);if(!a)throw err('AUDIT_LOG_NOT_FOUND','Audit log not found',404);return a;}
 async listAudits(input:Parameters<OperationsRepository['listAudits']>[1]){return this.repo.listAudits(this.db,input);}
 async bootstrap(authSubjectId:string,displayName:string){await this.requireActiveIdentity(authSubjectId);return this.tx.run(async db=>{await this.repo.lockBootstrap(db);if(await this.repo.countOperators(db)>0)throw err('BOOTSTRAP_ALREADY_COMPLETED','Operations bootstrap already completed',409);let role=await this.repo.findRoleByCode(db,'super_admin');if(!role)role=await this.repo.createRole(db,{id:randomUUID(),code:'super_admin',name:'Super Admin',description:'Reserved full-access Operations role'});if(role.status!=='active')throw err('SYSTEM_ROLE_PROTECTED','super_admin must be active',409);await this.repo.replaceRolePermissions(db,role.id,OPERATOR_PERMISSION_CATALOG);const operator=await this.repo.createOperator(db,{id:randomUUID(),authSubjectId,displayName:name(displayName)});await this.repo.addOperatorRole(db,operator.id,role.id);await this.repo.insertAudit(db,{id:randomUUID(),operatorId:operator.id,actionKey:'operations.operators.create',targetDomain:'operations',targetType:'operator',targetId:operator.id,details:{bootstrap:true,role_id:role.id}});return{operator,role};});}
}
