import { randomUUID } from 'node:crypto';
import { AppError } from '../../../../errors/app-error.js';
import type { AuthContext } from '../../../../auth/auth-context.js';
import type { DatabaseExecutor } from '../../../../database/executor.js';
import type { TransactionManager } from '../../../../database/transaction-manager.js';
import type { IdentityPublicQueries, UserPublicId } from '../../../identity/public/index.js';
import type { OperationsRepository, OperatorRecord, RoleRecord } from '../ports/index.js';
import { OPERATOR_PERMISSION_CATALOG, isOperatorPermissionKey, type AuthorizedOperatorContext, type OperatorPermissionKey, type OperationsAuditRecorder, type OperationsAuthorizer, type OperationsOperatorResolver, type OperatorSummary } from '../../public/index.js';

const appError=(code:string,message:string,httpStatus:number)=>new AppError({code,message,httpStatus});
const pgCode=(e:unknown):string|undefined=>typeof e==='object'&&e!==null&&'code' in e?String((e as {code?:unknown}).code):undefined;
const trimName=(s:string)=>{const v=s.trim();if(!v||v.length>100)throw appError('INVALID_ARGUMENT','Invalid display/name',400);return v;};
const ensureSafeDetails=(details:Readonly<Record<string,unknown>>={})=>{const text=JSON.stringify(details);if(text.length>8192)throw appError('INVALID_ARGUMENT','Audit details too large',400);if(/password|token|authorization|secret|card|payment_credential/i.test(text))throw appError('INVALID_ARGUMENT','Sensitive audit details are forbidden',400);return details;};

export class OperationsService implements OperationsAuthorizer, OperationsOperatorResolver, OperationsAuditRecorder {
 constructor(private readonly tx:TransactionManager, private readonly db:DatabaseExecutor, private readonly repo:OperationsRepository, private readonly identity:IdentityPublicQueries){}
 private async identityActive(subjectId:string){const summary=await this.identity.getIdentitySummary(subjectId as UserPublicId);if(!summary)throw appError('OPERATOR_AUTH_SUBJECT_NOT_FOUND','Identity subject not found',400);if(summary.status!=='active')throw appError('OPERATOR_AUTH_SUBJECT_INACTIVE','Identity subject is not active',409);}
 async resolveCurrentOperator(auth:AuthContext):Promise<OperatorSummary>{const operator=await this.repo.findOperatorByAuthSubjectId(this.db,auth.subjectId);if(!operator)throw appError('OPERATOR_ACCESS_DENIED','No active operator mapping',403);if(operator.status!=='active')throw appError('OPERATOR_DISABLED','Operator is disabled',403);return{operatorId:operator.id,authSubjectId:operator.authSubjectId,displayName:operator.displayName,status:operator.status};}
 async requirePermission(auth:AuthContext,permission:OperatorPermissionKey):Promise<AuthorizedOperatorContext>{const operator=await this.repo.findOperatorByAuthSubjectId(this.db,auth.subjectId);if(!operator)throw appError('OPERATOR_ACCESS_DENIED','No active operator mapping',403);if(operator.status!=='active')throw appError('OPERATOR_DISABLED','Operator is disabled',403);const permissions=await this.repo.getEffectivePermissions(this.db,operator.id);if(!permissions.includes(permission))throw appError('FORBIDDEN','Permission denied',403);return{operatorId:operator.id,authSubjectId:operator.authSubjectId};}
 async getCurrentOperator(auth:AuthContext){const operator=await this.resolveCurrentOperator(auth);const roles=await this.repo.listAssignedRoles(this.db,operator.operatorId);const permissions=await this.repo.getEffectivePermissions(this.db,operator.operatorId);return{operator,roles:roles.filter(r=>r.status==='active'),permissions:permissions.filter(isOperatorPermissionKey).sort()};}
 async recordSuccessfulAction(i:{operator:AuthorizedOperatorContext;actionKey:string;target?:{domain:string;type:string;id?:string};requestContext?:{requestId?:string;ipAddress?:string};details?:Readonly<Record<string,unknown>>}){try{await this.repo.insertAudit(this.db,{id:randomUUID(),operatorId:i.operator.operatorId,actionKey:i.actionKey,targetDomain:i.target?.domain,targetType:i.target?.type,targetId:i.target?.id,requestId:i.requestContext?.requestId,ipAddress:i.requestContext?.ipAddress,details:ensureSafeDetails(i.details)});}catch(cause){throw new AppError({code:'OPERATOR_AUDIT_PERSISTENCE_FAILED',message:'Operator action audit could not be persisted',httpStatus:500,expose:false,cause});}}
 private async localAudit(db:DatabaseExecutor,actor:AuthorizedOperatorContext,actionKey:string,target?:{domain:string;type:string;id?:string},details?:Readonly<Record<string,unknown>>){await this.repo.insertAudit(db,{id:randomUUID(),operatorId:actor.operatorId,actionKey,targetDomain:target?.domain,targetType:target?.type,targetId:target?.id,details:ensureSafeDetails(details)});}
 async listOperators(input:{page:number;pageSize:number;status?:'active'|'disabled'}){return this.repo.listOperators(this.db,input);}
 async getOperator(id:string){const o=await this.repo.findOperatorById(this.db,id);if(!o)throw appError('OPERATOR_NOT_FOUND','Operator not found',404);return o;}
 async createOperator(actor:AuthorizedOperatorContext,input:{authSubjectId:string;displayName:string}){await this.identityActive(input.authSubjectId);try{return await this.tx.run(async db=>{const o=await this.repo.createOperator(db,{id:randomUUID(),authSubjectId:input.authSubjectId,displayName:trimName(input.displayName)});await this.localAudit(db,actor,'operations.operators.create',{domain:'operations',type:'operator',id:o.id},{auth_subject_id:o.authSubjectId});return o;});}catch(e){if(pgCode(e)==='23505')throw appError('OPERATOR_ALREADY_EXISTS','Identity subject already mapped',409);throw e;}}
 async updateOperator(actor:AuthorizedOperatorContext,id:string,displayName:string){return this.tx.run(async db=>{const current=await this.repo.findOperatorById(db,id,true);if(!current)throw appError('OPERATOR_NOT_FOUND','Operator not found',404);const next=await this.repo.updateOperatorDisplayName(db,id,trimName(displayName));if(current.displayName!==next!.displayName)await this.localAudit(db,actor,'operations.operators.update',{domain:'operations',type:'operator',id});return next!;});}
 async setOperatorStatus(actor:AuthorizedOperatorContext,id:string,status:'active'|'disabled'){return this.tx.run(async db=>{const current=await this.repo.findOperatorById(db,id,true);if(!current)throw appError('OPERATOR_NOT_FOUND','Operator not found',404);if(current.status===status)return current;if(status==='active')await this.identityActive(current.authSubjectId);if(status==='disabled')await this.ensureNotLastSuperAdmin(db,id);const next=await this.repo.updateOperatorStatus(db,id,status);await this.localAudit(db,actor,`operations.operators.${status==='active'?'enable':'disable'}`,{domain:'operations',type:'operator',id});return next!;});}
 async listRoles(input:{page:number;pageSize:number;status?:'active'|'disabled'}){return this.repo.listRoles(this.db,input);}
 async getRole(id:string){const r=await this.repo.findRoleById(this.db,id);if(!r)throw appError('ROLE_NOT_FOUND','Role not found',404);return r;}
 async createRole(actor:AuthorizedOperatorContext,input:{code:string;name:string;description?:string|null}){if(input.code==='super_admin')throw appError('SYSTEM_ROLE_PROTECTED','super_admin is bootstrap-reserved',409);if(!/^[a-z][a-z0-9_]{0,49}$/.test(input.code))throw appError('INVALID_ARGUMENT','Invalid role code',400);try{return await this.tx.run(async db=>{const r=await this.repo.createRole(db,{id:randomUUID(),code:input.code,name:trimName(input.name),description:input.description?.trim()||null});await this.localAudit(db,actor,'operations.roles.create',{domain:'operations',type:'role',id:r.id},{code:r.code});return r;});}catch(e){if(pgCode(e)==='23505')throw appError('ROLE_CODE_CONFLICT','Role code already exists',409);throw e;}}
 async updateRole(actor:AuthorizedOperatorContext,id:string,input:{name?:string;description?:string|null}){return this.tx.run(async db=>{const current=await this.repo.findRoleById(db,id,true);if(!current)throw appError('ROLE_NOT_FOUND','Role not found',404);const next=await this.repo.updateRole(db,id,{name:input.name===undefined?undefined:trimName(input.name),description:input.description});if(JSON.stringify(current)!==JSON.stringify(next))await this.localAudit(db,actor,'operations.roles.update',{domain:'operations',type:'role',id});return next!;});}
 async setRoleStatus(actor:AuthorizedOperatorContext,id:string,status:'active'|'disabled'){return this.tx.run(async db=>{const current=await this.repo.findRoleById(db,id,true);if(!current)throw appError('ROLE_NOT_FOUND','Role not found',404);if(current.status===status)return current;if(current.code==='super_admin'&&status==='disabled')throw appError('SYSTEM_ROLE_PROTECTED','super_admin cannot be disabled',409);const next=await this.repo.updateRole(db,id,{status});await this.localAudit(db,actor,`operations.roles.${status==='active'?'enable':'disable'}`,{domain:'operations',type:'role',id});return next!;});}
 async listAssignedRoles(operatorId:string){await this.getOperator(operatorId);return this.repo.listAssignedRoles(this.db,operatorId);}
 async assignRole(actor:AuthorizedOperatorContext,operatorId:string,roleId:string){return this.tx.run(async db=>{const o=await this.repo.findOperatorById(db,operatorId,true);if(!o)throw appError('OPERATOR_NOT_FOUND','Operator not found',404);if(o.status!=='active')throw appError('OPERATOR_DISABLED','Target operator disabled',409);const r=await this.repo.findRoleById(db,roleId,true);if(!r)throw appError('ROLE_NOT_FOUND','Role not found',404);if(r.status!=='active')throw appError('ROLE_DISABLED','Role disabled',409);const changed=await this.repo.addOperatorRole(db,operatorId,roleId);if(changed)await this.localAudit(db,actor,'operations.operator_roles.assign',{domain:'operations',type:'operator',id:operatorId},{role_id:roleId});return changed;});}
 async revokeRole(actor:AuthorizedOperatorContext,operatorId:string,roleId:string){return this.tx.run(async db=>{const r=await this.repo.findRoleById(db,roleId,true);if(!r)throw appError('ROLE_NOT_FOUND','Role not found',404);if(r.code==='super_admin'&&await this.repo.hasOperatorRole(db,operatorId,roleId)){const count=await this.repo.countActiveOperatorsWithRole(db,roleId);const target=await this.repo.findOperatorById(db,operatorId,true);if(target?.status==='active'&&count<=1)throw appError('LAST_SUPER_ADMIN_REQUIRED','At least one active super-admin is required',409);}const changed=await this.repo.removeOperatorRole(db,operatorId,roleId);if(changed)await this.localAudit(db,actor,'operations.operator_roles.revoke',{domain:'operations',type:'operator',id:operatorId},{role_id:roleId});return changed;});}
 async listPermissionCatalog(){return OPERATOR_PERMISSION_CATALOG;}
 async listRolePermissions(roleId:string){await this.getRole(roleId);return this.repo.listRolePermissions(this.db,roleId);}
 async setRolePermissions(actor:AuthorizedOperatorContext,roleId:string,keys:readonly string[]){if(new Set(keys).size!==keys.length||keys.some(k=>!isOperatorPermissionKey(k)))throw appError('INVALID_PERMISSION','Invalid or duplicate permission',400);return this.tx.run(async db=>{const r=await this.repo.findRoleById(db,roleId,true);if(!r)throw appError('ROLE_NOT_FOUND','Role not found',404);if(r.code==='super_admin'&&(keys.length!==OPERATOR_PERMISSION_CATALOG.length||OPERATOR_PERMISSION_CATALOG.some(k=>!keys.includes(k))))throw appError('SYSTEM_ROLE_PROTECTED','super_admin must have the complete catalog',409);const diff=await this.repo.replaceRolePermissions(db,roleId,keys);if(diff.added.length||diff.removed.length)await this.localAudit(db,actor,'operations.role_permissions.set',{domain:'operations',type:'role',id:roleId},{added:diff.added,removed:diff.removed});return{permissions:(await this.repo.listRolePermissions(db,roleId)).filter(isOperatorPermissionKey),changed:diff.added.length>0||diff.removed.length>0};});}
 private async ensureNotLastSuperAdmin(db:DatabaseExecutor,operatorId:string){const r=await this.repo.findRoleByCode(db,'super_admin',true);if(!r||r.status!=='active'||!await this.repo.hasOperatorRole(db,operatorId,r.id))return;const count=await this.repo.countActiveOperatorsWithRole(db,r.id);if(count<=1)throw appError('LAST_SUPER_ADMIN_REQUIRED','At least one active super-admin is required',409);}
 async getAudit(id:string){const a=await this.repo.findAudit(this.db,id);if(!a)throw appError('AUDIT_LOG_NOT_FOUND','Audit log not found',404);return a;}
 async listAudits(input:Parameters<OperationsRepository['listAudits']>[1]){return this.repo.listAudits(this.db,input);}
 async bootstrap(authSubjectId:string,displayName:string){await this.identityActive(authSubjectId);return this.tx.run(async db=>{if(await this.repo.countOperators(db)>0)throw appError('BOOTSTRAP_ALREADY_COMPLETED','Operations bootstrap already completed',409);let role=await this.repo.findRoleByCode(db,'super_admin',true);if(!role)role=await this.repo.createRole(db,{id:randomUUID(),code:'super_admin',name:'Super Admin',description:'Reserved full-access Operations role'});if(role.status!=='active')throw appError('SYSTEM_ROLE_PROTECTED','super_admin must be active',409);await this.repo.replaceRolePermissions(db,role.id,OPERATOR_PERMISSION_CATALOG);const operator=await this.repo.createOperator(db,{id:randomUUID(),authSubjectId,displayName:trimName(displayName)});await this.repo.addOperatorRole(db,operator.id,role.id);await this.repo.insertAudit(db,{id:randomUUID(),operatorId:operator.id,actionKey:'operations.operators.create',targetDomain:'operations',targetType:'operator',targetId:operator.id,details:{bootstrap:true,role_id:role.id}});return{operator,role};});}
}
