/**
 * 业务状态码词汇表（Business Status Code Vocabulary）。
 *
 * ADR-023 权威登记：`docs/docs/developer/reference/architecture/applications/business-status-codes.md`
 * （frozen）。业务状态码是前后端判断成败与分支的唯一权威（HTTP 一律 200）。
 * 新增业务码必须先登记词汇表，再在此枚举中添加，禁止各域自造冲突码。
 *
 * 分组与词汇表文件一一对应：通用成功 / 通用失败 / Identity / OTP / Platform / Operations / Content。
 * Content 域内联错误码已统一为 AppError（UNICODE_CONFLICT / ACTIVE_WORK_CONFLICT /
 * ILLEGAL_STATE_TRANSITION），纳入本枚举。
 */

/** 通用成功码 */
export const OK = 'OK' as const;

/** 通用失败码 */
export const UNAUTHENTICATED = 'UNAUTHENTICATED' as const;
export const FORBIDDEN = 'FORBIDDEN' as const;
export const NOT_FOUND = 'NOT_FOUND' as const;
export const VALIDATION_ERROR = 'VALIDATION_ERROR' as const;
export const STALE_VERSION_CONFLICT = 'STALE_VERSION_CONFLICT' as const;
export const CONFLICT = 'CONFLICT' as const;
export const RATE_LIMITED = 'RATE_LIMITED' as const;
export const BATCH_SELECTION_CHANGED = 'BATCH_SELECTION_CHANGED' as const;
export const BATCH_TASK_NOT_RETRYABLE = 'BATCH_TASK_NOT_RETRYABLE' as const;
export const LOGIN_RATE_LIMITED = 'LOGIN_RATE_LIMITED' as const;
export const INTERNAL_ERROR = 'INTERNAL_ERROR' as const;
export const INVALID_ARGUMENT = 'INVALID_ARGUMENT' as const;
export const INVALID_DATA = 'INVALID_DATA' as const;
export const INVALID_REQUEST = 'INVALID_REQUEST' as const;
export const PROVIDER_UNAVAILABLE = 'PROVIDER_UNAVAILABLE' as const;

/** Identity 域 */
export const INVALID_CREDENTIAL = 'INVALID_CREDENTIAL' as const;
export const ACCOUNT_DISABLED = 'ACCOUNT_DISABLED' as const;
export const ACCOUNT_CLOSED = 'ACCOUNT_CLOSED' as const;
export const SESSION_EXPIRED = 'SESSION_EXPIRED' as const;
export const SESSION_REVOKED = 'SESSION_REVOKED' as const;
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED' as const;
export const DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND' as const;
export const DEVICE_REVOKED = 'DEVICE_REVOKED' as const;
export const DEVICE_OWNERSHIP_CONFLICT = 'DEVICE_OWNERSHIP_CONFLICT' as const;
export const PHONE_ALREADY_BOUND = 'PHONE_ALREADY_BOUND' as const;
export const PHONE_NOT_BOUND = 'PHONE_NOT_BOUND' as const;
export const INVALID_PHONE = 'INVALID_PHONE' as const;
export const IDENTITY_CONFLICT = 'IDENTITY_CONFLICT' as const;
export const IDENTITY_EMPTY_PROFILE_UPDATE = 'IDENTITY_EMPTY_PROFILE_UPDATE' as const;
export const IDENTITY_REFERENTIAL_CONFLICT = 'IDENTITY_REFERENTIAL_CONFLICT' as const;
export const IDENTITY_REPOSITORY_FAILURE = 'IDENTITY_REPOSITORY_FAILURE' as const;
export const LEARNING_DIRECTION_IMMUTABLE = 'LEARNING_DIRECTION_IMMUTABLE' as const;
export const PASSWORD_CHANGE_REQUIRED = 'PASSWORD_CHANGE_REQUIRED' as const;

/** OTP 域（Identity） */
export const OTP_ALREADY_USED = 'OTP_ALREADY_USED' as const;
export const OTP_EXPIRED = 'OTP_EXPIRED' as const;
export const OTP_LOCKED = 'OTP_LOCKED' as const;
export const OTP_INVALID = 'OTP_INVALID' as const;
export const OTP_RATE_LIMITED = 'OTP_RATE_LIMITED' as const;
export const OTP_SECRET_INVALID = 'OTP_SECRET_INVALID' as const;
export const BOOTSTRAP_ALREADY_COMPLETED = 'BOOTSTRAP_ALREADY_COMPLETED' as const;

/** Platform 域 */
export const PLATFORM_INVALID_ARGUMENT = 'PLATFORM_INVALID_ARGUMENT' as const;
export const PLATFORM_NOT_FOUND = 'PLATFORM_NOT_FOUND' as const;
export const PLATFORM_CONFLICT = 'PLATFORM_CONFLICT' as const;
export const FEATURE_FLAG_INVALID_SCOPE = 'FEATURE_FLAG_INVALID_SCOPE' as const;
export const FEATURE_FLAG_RETIRED = 'FEATURE_FLAG_RETIRED' as const;
export const RUNTIME_CONFIG_INVALID_VALUE = 'RUNTIME_CONFIG_INVALID_VALUE' as const;
export const RUNTIME_CONFIG_KEY_UNREGISTERED = 'RUNTIME_CONFIG_KEY_UNREGISTERED' as const;
export const RUNTIME_CONFIG_RETIRED = 'RUNTIME_CONFIG_RETIRED' as const;
export const RUNTIME_CONFIG_UNAVAILABLE = 'RUNTIME_CONFIG_UNAVAILABLE' as const;
export const APP_VERSION_MISMATCH = 'APP_VERSION_MISMATCH' as const;
export const APP_VERSION_INVALID_TRANSITION = 'APP_VERSION_INVALID_TRANSITION' as const;
export const APP_VERSION_POLICY_UNAVAILABLE = 'APP_VERSION_POLICY_UNAVAILABLE' as const;
export const ANNOUNCEMENT_INVALID_TRANSITION = 'ANNOUNCEMENT_INVALID_TRANSITION' as const;
export const REGION_INVALID = 'REGION_INVALID' as const;
export const REGION_RETIRED = 'REGION_RETIRED' as const;

/** Operations 域 */
export const OPERATOR_ACCESS_DENIED = 'OPERATOR_ACCESS_DENIED' as const;
export const OPERATOR_DISABLED = 'OPERATOR_DISABLED' as const;
export const OPERATOR_PASSWORD_RESET_NOT_ALLOWED = 'OPERATOR_PASSWORD_RESET_NOT_ALLOWED' as const;
export const OPERATOR_NOT_FOUND = 'OPERATOR_NOT_FOUND' as const;
export const OPERATOR_ALREADY_EXISTS = 'OPERATOR_ALREADY_EXISTS' as const;
export const ADMIN_USERNAME_CONFLICT = 'ADMIN_USERNAME_CONFLICT' as const;
export const OPERATOR_AUTH_SUBJECT_NOT_FOUND = 'OPERATOR_AUTH_SUBJECT_NOT_FOUND' as const;
export const OPERATOR_AUTH_SUBJECT_INACTIVE = 'OPERATOR_AUTH_SUBJECT_INACTIVE' as const;
export const ROLE_NOT_FOUND = 'ROLE_NOT_FOUND' as const;
export const ROLE_DISABLED = 'ROLE_DISABLED' as const;
export const ROLE_CODE_CONFLICT = 'ROLE_CODE_CONFLICT' as const;
export const INVALID_PERMISSION = 'INVALID_PERMISSION' as const;
export const LAST_SUPER_ADMIN_REQUIRED = 'LAST_SUPER_ADMIN_REQUIRED' as const;
export const SYSTEM_ROLE_PROTECTED = 'SYSTEM_ROLE_PROTECTED' as const;
export const AUDIT_LOG_NOT_FOUND = 'AUDIT_LOG_NOT_FOUND' as const;
export const OPERATOR_AUDIT_PERSISTENCE_FAILED = 'OPERATOR_AUDIT_PERSISTENCE_FAILED' as const;
export const AUTHENTICATION_UNAVAILABLE = 'AUTHENTICATION_UNAVAILABLE' as const;

/** Content 域（统一后入词汇表） */
export const UNICODE_CONFLICT = 'UNICODE_CONFLICT' as const;
export const ACTIVE_WORK_CONFLICT = 'ACTIVE_WORK_CONFLICT' as const;
export const ILLEGAL_STATE_TRANSITION = 'ILLEGAL_STATE_TRANSITION' as const;

/** 全部业务状态码联合类型（UPPER_SNAKE_CASE） */
export type BusinessStatusCode =
  | typeof OK
  | typeof UNAUTHENTICATED
  | typeof FORBIDDEN
  | typeof NOT_FOUND
  | typeof VALIDATION_ERROR
  | typeof STALE_VERSION_CONFLICT
  | typeof CONFLICT
  | typeof RATE_LIMITED
  | typeof BATCH_SELECTION_CHANGED
  | typeof BATCH_TASK_NOT_RETRYABLE
  | typeof LOGIN_RATE_LIMITED
  | typeof INTERNAL_ERROR
  | typeof INVALID_ARGUMENT
  | typeof INVALID_DATA
  | typeof INVALID_REQUEST
  | typeof PROVIDER_UNAVAILABLE
  | typeof INVALID_CREDENTIAL
  | typeof ACCOUNT_DISABLED
  | typeof ACCOUNT_CLOSED
  | typeof SESSION_EXPIRED
  | typeof SESSION_REVOKED
  | typeof TOKEN_EXPIRED
  | typeof DEVICE_NOT_FOUND
  | typeof DEVICE_REVOKED
  | typeof DEVICE_OWNERSHIP_CONFLICT
  | typeof PHONE_ALREADY_BOUND
  | typeof PHONE_NOT_BOUND
  | typeof INVALID_PHONE
  | typeof IDENTITY_CONFLICT
  | typeof IDENTITY_EMPTY_PROFILE_UPDATE
  | typeof IDENTITY_REFERENTIAL_CONFLICT
  | typeof IDENTITY_REPOSITORY_FAILURE
  | typeof LEARNING_DIRECTION_IMMUTABLE
  | typeof PASSWORD_CHANGE_REQUIRED
  | typeof OTP_ALREADY_USED
  | typeof OTP_EXPIRED
  | typeof OTP_LOCKED
  | typeof OTP_INVALID
  | typeof OTP_RATE_LIMITED
  | typeof OTP_SECRET_INVALID
  | typeof BOOTSTRAP_ALREADY_COMPLETED
  | typeof PLATFORM_INVALID_ARGUMENT
  | typeof PLATFORM_NOT_FOUND
  | typeof PLATFORM_CONFLICT
  | typeof FEATURE_FLAG_INVALID_SCOPE
  | typeof FEATURE_FLAG_RETIRED
  | typeof RUNTIME_CONFIG_INVALID_VALUE
  | typeof RUNTIME_CONFIG_KEY_UNREGISTERED
  | typeof RUNTIME_CONFIG_RETIRED
  | typeof RUNTIME_CONFIG_UNAVAILABLE
  | typeof APP_VERSION_MISMATCH
  | typeof APP_VERSION_INVALID_TRANSITION
  | typeof APP_VERSION_POLICY_UNAVAILABLE
  | typeof ANNOUNCEMENT_INVALID_TRANSITION
  | typeof REGION_INVALID
  | typeof REGION_RETIRED
  | typeof OPERATOR_ACCESS_DENIED
  | typeof OPERATOR_DISABLED
  | typeof OPERATOR_PASSWORD_RESET_NOT_ALLOWED
  | typeof OPERATOR_NOT_FOUND
  | typeof OPERATOR_ALREADY_EXISTS
  | typeof ADMIN_USERNAME_CONFLICT
  | typeof OPERATOR_AUTH_SUBJECT_NOT_FOUND
  | typeof OPERATOR_AUTH_SUBJECT_INACTIVE
  | typeof ROLE_NOT_FOUND
  | typeof ROLE_DISABLED
  | typeof ROLE_CODE_CONFLICT
  | typeof INVALID_PERMISSION
  | typeof LAST_SUPER_ADMIN_REQUIRED
  | typeof SYSTEM_ROLE_PROTECTED
  | typeof AUDIT_LOG_NOT_FOUND
  | typeof OPERATOR_AUDIT_PERSISTENCE_FAILED
  | typeof AUTHENTICATION_UNAVAILABLE
  | typeof UNICODE_CONFLICT
  | typeof ACTIVE_WORK_CONFLICT
  | typeof ILLEGAL_STATE_TRANSITION;

/**
 * 全部业务状态码数组（用于运行时校验/交叉校验）。
 * 与 `business-status-codes.md` 词汇表一一对应。
 */
export const BUSINESS_STATUS_CODES: readonly BusinessStatusCode[] = [
  OK,
  UNAUTHENTICATED, FORBIDDEN, NOT_FOUND, VALIDATION_ERROR, STALE_VERSION_CONFLICT,
  CONFLICT, RATE_LIMITED, BATCH_SELECTION_CHANGED, BATCH_TASK_NOT_RETRYABLE, LOGIN_RATE_LIMITED, INTERNAL_ERROR, INVALID_ARGUMENT,
  INVALID_DATA, INVALID_REQUEST, PROVIDER_UNAVAILABLE,
  INVALID_CREDENTIAL, ACCOUNT_DISABLED, ACCOUNT_CLOSED, SESSION_EXPIRED,
  SESSION_REVOKED, TOKEN_EXPIRED, DEVICE_NOT_FOUND, DEVICE_REVOKED,
  DEVICE_OWNERSHIP_CONFLICT, PHONE_ALREADY_BOUND, PHONE_NOT_BOUND, INVALID_PHONE,
  IDENTITY_CONFLICT, IDENTITY_EMPTY_PROFILE_UPDATE, IDENTITY_REFERENTIAL_CONFLICT,
  IDENTITY_REPOSITORY_FAILURE, LEARNING_DIRECTION_IMMUTABLE, PASSWORD_CHANGE_REQUIRED,
  OTP_ALREADY_USED, OTP_EXPIRED, OTP_LOCKED, OTP_INVALID, OTP_RATE_LIMITED,
  OTP_SECRET_INVALID, BOOTSTRAP_ALREADY_COMPLETED,
  PLATFORM_INVALID_ARGUMENT, PLATFORM_NOT_FOUND, PLATFORM_CONFLICT,
  FEATURE_FLAG_INVALID_SCOPE, FEATURE_FLAG_RETIRED, RUNTIME_CONFIG_INVALID_VALUE,
  RUNTIME_CONFIG_KEY_UNREGISTERED, RUNTIME_CONFIG_RETIRED, RUNTIME_CONFIG_UNAVAILABLE,
  APP_VERSION_MISMATCH, APP_VERSION_INVALID_TRANSITION, APP_VERSION_POLICY_UNAVAILABLE,
  ANNOUNCEMENT_INVALID_TRANSITION, REGION_INVALID, REGION_RETIRED,
  OPERATOR_ACCESS_DENIED, OPERATOR_DISABLED, OPERATOR_PASSWORD_RESET_NOT_ALLOWED, OPERATOR_NOT_FOUND, OPERATOR_ALREADY_EXISTS, ADMIN_USERNAME_CONFLICT,
  OPERATOR_AUTH_SUBJECT_NOT_FOUND, OPERATOR_AUTH_SUBJECT_INACTIVE, ROLE_NOT_FOUND,
  ROLE_DISABLED, ROLE_CODE_CONFLICT, INVALID_PERMISSION, LAST_SUPER_ADMIN_REQUIRED,
  SYSTEM_ROLE_PROTECTED, AUDIT_LOG_NOT_FOUND, OPERATOR_AUDIT_PERSISTENCE_FAILED,
  AUTHENTICATION_UNAVAILABLE, UNICODE_CONFLICT, ACTIVE_WORK_CONFLICT, ILLEGAL_STATE_TRANSITION,
] as const;

/** 业务码 → 原 HTTP 状态码参考语义（仅日志/监控/兼容说明，不决定响应码） */
export const BUSINESS_HTTP_REF: Readonly<Record<BusinessStatusCode, number>> = {
  OK: 200,
  UNAUTHENTICATED: 401, FORBIDDEN: 403, NOT_FOUND: 404, VALIDATION_ERROR: 400,
  STALE_VERSION_CONFLICT: 409, CONFLICT: 409, RATE_LIMITED: 429, BATCH_SELECTION_CHANGED: 409, BATCH_TASK_NOT_RETRYABLE: 409,
  LOGIN_RATE_LIMITED: 429, INTERNAL_ERROR: 500, INVALID_ARGUMENT: 400,
  INVALID_DATA: 400, INVALID_REQUEST: 400, PROVIDER_UNAVAILABLE: 503,
  INVALID_CREDENTIAL: 401, ACCOUNT_DISABLED: 403, ACCOUNT_CLOSED: 403,
  SESSION_EXPIRED: 401, SESSION_REVOKED: 401, TOKEN_EXPIRED: 401,
  DEVICE_NOT_FOUND: 404, DEVICE_REVOKED: 401, DEVICE_OWNERSHIP_CONFLICT: 409,
  PHONE_ALREADY_BOUND: 409, PHONE_NOT_BOUND: 404, INVALID_PHONE: 400,
  IDENTITY_CONFLICT: 409, IDENTITY_EMPTY_PROFILE_UPDATE: 400,
  IDENTITY_REFERENTIAL_CONFLICT: 409, IDENTITY_REPOSITORY_FAILURE: 500,
  LEARNING_DIRECTION_IMMUTABLE: 409,
  PASSWORD_CHANGE_REQUIRED: 403,
  OTP_ALREADY_USED: 409, OTP_EXPIRED: 400, OTP_LOCKED: 400, OTP_INVALID: 400,
  OTP_RATE_LIMITED: 429, OTP_SECRET_INVALID: 400, BOOTSTRAP_ALREADY_COMPLETED: 409,
  PLATFORM_INVALID_ARGUMENT: 400, PLATFORM_NOT_FOUND: 404, PLATFORM_CONFLICT: 409,
  FEATURE_FLAG_INVALID_SCOPE: 400, FEATURE_FLAG_RETIRED: 409,
  RUNTIME_CONFIG_INVALID_VALUE: 400, RUNTIME_CONFIG_KEY_UNREGISTERED: 400,
  RUNTIME_CONFIG_RETIRED: 409, RUNTIME_CONFIG_UNAVAILABLE: 404,
  APP_VERSION_MISMATCH: 409, APP_VERSION_INVALID_TRANSITION: 409,
  APP_VERSION_POLICY_UNAVAILABLE: 404, ANNOUNCEMENT_INVALID_TRANSITION: 409,
  REGION_INVALID: 400, REGION_RETIRED: 409,
  OPERATOR_ACCESS_DENIED: 403, OPERATOR_DISABLED: 403, OPERATOR_PASSWORD_RESET_NOT_ALLOWED: 409, OPERATOR_NOT_FOUND: 404,
  OPERATOR_ALREADY_EXISTS: 409, ADMIN_USERNAME_CONFLICT: 409, OPERATOR_AUTH_SUBJECT_NOT_FOUND: 400,
  OPERATOR_AUTH_SUBJECT_INACTIVE: 409, ROLE_NOT_FOUND: 404, ROLE_DISABLED: 409,
  ROLE_CODE_CONFLICT: 409, INVALID_PERMISSION: 400, LAST_SUPER_ADMIN_REQUIRED: 409,
  SYSTEM_ROLE_PROTECTED: 409, AUDIT_LOG_NOT_FOUND: 404,
  OPERATOR_AUDIT_PERSISTENCE_FAILED: 500, AUTHENTICATION_UNAVAILABLE: 503,
  UNICODE_CONFLICT: 409, ACTIVE_WORK_CONFLICT: 409, ILLEGAL_STATE_TRANSITION: 400,
} as const;
